#!/usr/bin/env python3
"""
Добавление полной теории и практики в MLP notebook
"""

import json

# Читаем текущий ноутбук
notebook_path = '01_mlp_basics.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

new_cells = []

# ============================================================================
# THEORY: ACTIVATION FUNCTIONS
# ============================================================================

new_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.2 Функции активации\n",
        "\n",
        "**Зачем нужны?** Без нелинейной активации, многослойная сеть = линейная модель!\n",
        "\n",
        "#### 1.2.1 Sigmoid\n",
        "\n",
        "$$\\sigma(x) = \\frac{1}{1 + e^{-x}}$$\n",
        "\n",
        "**Свойства:**\n",
        "- Выход: $(0, 1)$\n",
        "- ✅ Интерпретация как вероятность\n",
        "- ❌ **Vanishing gradient** для больших $|x|$\n",
        "- ❌ **Not zero-centered** (все производные положительны)\n",
        "\n",
        "**Производная:**\n",
        "\n",
        "$$\\sigma'(x) = \\sigma(x)(1 - \\sigma(x))$$\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.2.2 Tanh\n",
        "\n",
        "$$\\tanh(x) = \\frac{e^x - e^{-x}}{e^x + e^{-x}}$$\n",
        "\n",
        "**Свойства:**\n",
        "- Выход: $(-1, 1)$\n",
        "- ✅ **Zero-centered**\n",
        "- ❌ **Vanishing gradient** для больших $|x|$\n",
        "\n",
        "**Производная:**\n",
        "\n",
        "$$\\tanh'(x) = 1 - \\tanh^2(x)$$\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.2.3 ReLU (Rectified Linear Unit) ⭐\n",
        "\n",
        "$$\\text{ReLU}(x) = \\max(0, x)$$\n",
        "\n",
        "**Свойства:**\n",
        "- ✅ **Простота вычислений**\n",
        "- ✅ **Нет vanishing gradient** для $x > 0$\n",
        "- ✅ **Sparse activations** (многие нейроны = 0)\n",
        "- ❌ **Dying ReLU** проблема (нейроны \"умирают\" при $x \\leq 0$)\n",
        "\n",
        "**Производная:**\n",
        "\n",
        "$$\\text{ReLU}'(x) = \\begin{cases} 1, & \\text{if } x > 0 \\\\ 0, & \\text{if } x \\leq 0 \\end{cases}$$\n",
        "\n",
        "**Почему ReLU стал стандартом?**\n",
        "- Faster convergence (до 6x быстрее, чем sigmoid/tanh)\n",
        "- Simplicity\n",
        "- Биологически правдоподобно\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.2.4 Leaky ReLU\n",
        "\n",
        "$$\\text{LeakyReLU}(x) = \\max(0.01x, x)$$\n",
        "\n",
        "**Решает dying ReLU:**\n",
        "- Малый градиент (0.01) для $x < 0$ вместо 0\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.2.5 ELU (Exponential Linear Unit)\n",
        "\n",
        "$$\\text{ELU}(x) = \\begin{cases} x, & \\text{if } x > 0 \\\\ \\alpha(e^x - 1), & \\text{if } x \\leq 0 \\end{cases}$$\n",
        "\n",
        "**Свойства:**\n",
        "- ✅ Smooth везде\n",
        "- ✅ Mean activations ближе к нулю\n",
        "- ❌ Медленнее ReLU (экспонента)\n",
        "\n",
        "---\n",
        "\n",
        "#### Сравнение активаций\n",
        "\n",
        "| Активация | Vanishing Gradient | Dying Units | Скорость | Рекомендация |\n",
        "|-----------|-------------------|-------------|----------|-------------|\n",
        "| **Sigmoid** | ❌ Да | ✅ Нет | Slow | Только output для binary |\n",
        "| **Tanh** | ❌ Да | ✅ Нет | Slow | RNN (иногда) |\n",
        "| **ReLU** | ✅ Нет | ❌ Да | ⚡ Fast | ⭐ Стандарт для hidden |\n",
        "| **Leaky ReLU** | ✅ Нет | ✅ Нет | ⚡ Fast | Альтернатива ReLU |\n",
        "| **ELU** | ✅ Нет | ✅ Нет | Slower | Когда нужна гладкость |\n",
        "\n",
        "**Практическая рекомендация:**\n",
        "1. **Default:** ReLU для всех скрытых слоев\n",
        "2. **Если dying ReLU проблема:** Leaky ReLU или ELU\n",
        "3. **Output layer (binary):** Sigmoid\n",
        "4. **Output layer (multiclass):** Softmax\n",
        "5. **Output layer (regression):** Linear (no activation)\n",
        "\n",
        "---"
    ]
})

# ============================================================================
# THEORY: BACKPROPAGATION
# ============================================================================

new_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.3 Backpropagation и Gradient Descent\n",
        "\n",
        "#### Loss Function\n",
        "\n",
        "**Binary Cross-Entropy (для classification):**\n",
        "\n",
        "$$L = -\\frac{1}{N} \\sum_{i=1}^N \\left[ y_i \\log(\\hat{y}_i) + (1 - y_i) \\log(1 - \\hat{y}_i) \\right]$$\n",
        "\n",
        "где:\n",
        "- $y_i$ — истинная метка (0 или 1)\n",
        "- $\\hat{y}_i$ — предсказанная вероятность\n",
        "\n",
        "**Mean Squared Error (для regression):**\n",
        "\n",
        "$$L = \\frac{1}{N} \\sum_{i=1}^N (y_i - \\hat{y}_i)^2$$\n",
        "\n",
        "---\n",
        "\n",
        "#### Backpropagation Algorithm\n",
        "\n",
        "**Цель:** Вычислить $\\frac{\\partial L}{\\partial W^{(l)}}$ для всех слоев.\n",
        "\n",
        "**Chain rule:**\n",
        "\n",
        "$$\\frac{\\partial L}{\\partial W^{(l)}} = \\frac{\\partial L}{\\partial a^{(L)}} \\cdot \\frac{\\partial a^{(L)}}{\\partial z^{(L)}} \\cdot \\ldots \\cdot \\frac{\\partial z^{(l)}}{\\partial W^{(l)}}$$\n",
        "\n",
        "**Алгоритм:**\n",
        "\n",
        "1. **Forward pass:** Вычислить $a^{(l)}$ для всех слоев\n",
        "2. **Compute loss:** $L = \\text{loss}(a^{(L)}, y)$\n",
        "3. **Backward pass:** \n",
        "   - Вычислить $\\delta^{(L)} = \\frac{\\partial L}{\\partial z^{(L)}}$\n",
        "   - Для $l = L-1, L-2, \\ldots, 1$:\n",
        "     $$\\delta^{(l)} = (W^{(l+1)})^T \\delta^{(l+1)} \\odot \\sigma'(z^{(l)})$$\n",
        "   - Градиенты весов:\n",
        "     $$\\frac{\\partial L}{\\partial W^{(l)}} = \\delta^{(l)} (a^{(l-1)})^T$$\n",
        "\n",
        "4. **Update weights:**\n",
        "   $$W^{(l)} \\leftarrow W^{(l)} - \\eta \\frac{\\partial L}{\\partial W^{(l)}}$$\n",
        "\n",
        "где $\\eta$ — learning rate.\n",
        "\n",
        "---\n",
        "\n",
        "#### Gradient Descent варианты\n",
        "\n",
        "**1. Batch Gradient Descent:**\n",
        "- Используем **все** данные для вычисления градиента\n",
        "- ✅ Stable convergence\n",
        "- ❌ Slow для больших данных\n",
        "\n",
        "**2. Stochastic Gradient Descent (SGD):**\n",
        "- Используем **один** пример за раз\n",
        "- ✅ Fast updates\n",
        "- ❌ Noisy gradient, может не сойтись\n",
        "\n",
        "**3. Mini-Batch Gradient Descent:** ⭐\n",
        "- Используем **batch** примеров (обычно 32, 64, 128, 256)\n",
        "- ✅ Баланс скорости и стабильности\n",
        "- ✅ Эффективное использование GPU\n",
        "\n",
        "---"
    ]
})

# ============================================================================
# THEORY: OPTIMIZERS
# ============================================================================

new_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.4 Оптимизаторы\n",
        "\n",
        "#### 1.4.1 SGD (Stochastic Gradient Descent)\n",
        "\n",
        "$$W_{t+1} = W_t - \\eta \\nabla L(W_t)$$\n",
        "\n",
        "**Проблемы:**\n",
        "- ❌ Одинаковый learning rate для всех параметров\n",
        "- ❌ Может застрять в локальных минимумах\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.4.2 SGD with Momentum\n",
        "\n",
        "$$\n",
        "\\begin{align}\n",
        "v_t &= \\beta v_{t-1} + \\nabla L(W_t) \\\\\n",
        "W_{t+1} &= W_t - \\eta v_t\n",
        "\\end{align}\n",
        "$$\n",
        "\n",
        "где $\\beta$ (обычно 0.9) — momentum coefficient.\n",
        "\n",
        "**Эффект:**\n",
        "- ✅ Ускорение в правильном направлении\n",
        "- ✅ Подавление колебаний\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.4.3 RMSprop (Root Mean Square Propagation)\n",
        "\n",
        "$$\n",
        "\\begin{align}\n",
        "E[g^2]_t &= \\beta E[g^2]_{t-1} + (1-\\beta) (\\nabla L)^2 \\\\\n",
        "W_{t+1} &= W_t - \\frac{\\eta}{\\sqrt{E[g^2]_t + \\epsilon}} \\nabla L\n",
        "\\end{align}\n",
        "$$\n",
        "\n",
        "**Эффект:**\n",
        "- ✅ Адаптивный learning rate для каждого параметра\n",
        "- ✅ Малые обновления для параметров с большими градиентами\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.4.4 Adam (Adaptive Moment Estimation) ⭐\n",
        "\n",
        "**Комбинация Momentum + RMSprop:**\n",
        "\n",
        "$$\n",
        "\\begin{align}\n",
        "m_t &= \\beta_1 m_{t-1} + (1 - \\beta_1) \\nabla L \\quad \\text{(1st moment, momentum)} \\\\\n",
        "v_t &= \\beta_2 v_{t-1} + (1 - \\beta_2) (\\nabla L)^2 \\quad \\text{(2nd moment, RMSprop)} \\\\\n",
        "\\hat{m}_t &= \\frac{m_t}{1 - \\beta_1^t} \\quad \\text{(bias correction)} \\\\\n",
        "\\hat{v}_t &= \\frac{v_t}{1 - \\beta_2^t} \\\\\n",
        "W_{t+1} &= W_t - \\frac{\\eta}{\\sqrt{\\hat{v}_t} + \\epsilon} \\hat{m}_t\n",
        "\\end{align}\n",
        "$$\n",
        "\n",
        "**Default параметры:**\n",
        "- $\\beta_1 = 0.9$\n",
        "- $\\beta_2 = 0.999$\n",
        "- $\\epsilon = 10^{-8}$\n",
        "\n",
        "**Почему Adam лучший?**\n",
        "- ✅ Adaptive learning rates\n",
        "- ✅ Работает out-of-the-box для большинства задач\n",
        "- ✅ Меньше tuning, чем SGD\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.4.5 AdamW\n",
        "\n",
        "Adam + **decoupled weight decay:**\n",
        "\n",
        "$$W_{t+1} = W_t - \\frac{\\eta}{\\sqrt{\\hat{v}_t} + \\epsilon} \\hat{m}_t - \\eta \\lambda W_t$$\n",
        "\n",
        "где $\\lambda$ — weight decay coefficient.\n",
        "\n",
        "**Улучшение:** Правильная L2 регуляризация (в Adam была ошибка).\n",
        "\n",
        "---\n",
        "\n",
        "#### Сравнение оптимизаторов\n",
        "\n",
        "| Оптимизатор | Скорость сходимости | Tuning сложность | Рекомендация |\n",
        "|-------------|-------------------|------------------|-------------|\n",
        "| **SGD** | Slow | High (LR, momentum) | Когда нужна стабильность |\n",
        "| **SGD + Momentum** | Medium | Medium | Computer Vision (иногда) |\n",
        "| **RMSprop** | Fast | Low | RNN (исторически) |\n",
        "| **Adam** | ⚡ Fast | ⭐ Very Low | **Default для большинства задач** |\n",
        "| **AdamW** | ⚡ Fast | ⭐ Very Low | Transformers, modern DL |\n",
        "\n",
        "**Практическая рекомендация:**\n",
        "1. **Start with Adam** (lr=0.001)\n",
        "2. Если переобучение → AdamW (weight_decay=0.01)\n",
        "3. Для CV иногда SGD+Momentum лучше (но нужен tuning)\n",
        "\n",
        "---"
    ]
})

# ============================================================================
# THEORY: REGULARIZATION
# ============================================================================

new_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.5 Регуляризация и Batch Normalization\n",
        "\n",
        "#### 1.5.1 Dropout\n",
        "\n",
        "**Идея:** Случайно \"выключать\" нейроны во время обучения.\n",
        "\n",
        "**Алгоритм (training):**\n",
        "```python\n",
        "for each neuron:\n",
        "    with probability p:\n",
        "        set activation to 0\n",
        "    else:\n",
        "        keep activation / (1-p)  # scaling\n",
        "```\n",
        "\n",
        "**При inference:** All neurons active (no dropout).\n",
        "\n",
        "**Математически:**\n",
        "\n",
        "$$a_i^{\\text{train}} = \\frac{1}{1-p} \\cdot a_i \\cdot r_i$$\n",
        "\n",
        "где $r_i \\sim \\text{Bernoulli}(1-p)$.\n",
        "\n",
        "**Почему работает?**\n",
        "- ✅ **Ensemble эффект:** Обучаем много \"подсетей\"\n",
        "- ✅ **Предотвращение co-adaptation:** Нейроны не могут полагаться на конкретные другие\n",
        "- ✅ **Regularization:** Уменьшает overfitting\n",
        "\n",
        "**Типичные значения:**\n",
        "- $p = 0.2$ для входного слоя\n",
        "- $p = 0.5$ для скрытых слоев\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.5.2 L1/L2 Regularization\n",
        "\n",
        "**L2 (Weight Decay):**\n",
        "\n",
        "$$L_{\\text{total}} = L_{\\text{data}} + \\frac{\\lambda}{2} \\sum_i w_i^2$$\n",
        "\n",
        "**Эффект:** Малые веса → проще модель → меньше overfitting.\n",
        "\n",
        "**L1 (Lasso):**\n",
        "\n",
        "$$L_{\\text{total}} = L_{\\text{data}} + \\lambda \\sum_i |w_i|$$\n",
        "\n",
        "**Эффект:** Sparse weights (многие = 0) → feature selection.\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.5.3 Batch Normalization\n",
        "\n",
        "**Проблема:** Internal covariate shift — распределение активаций меняется во время обучения.\n",
        "\n",
        "**Решение:** Нормализация активаций для каждого mini-batch.\n",
        "\n",
        "**Алгоритм:**\n",
        "\n",
        "Для batch $B = \\{x_1, \\ldots, x_m\\}$:\n",
        "\n",
        "$$\n",
        "\\begin{align}\n",
        "\\mu_B &= \\frac{1}{m} \\sum_{i=1}^m x_i \\quad \\text{(mean)} \\\\\n",
        "\\sigma_B^2 &= \\frac{1}{m} \\sum_{i=1}^m (x_i - \\mu_B)^2 \\quad \\text{(variance)} \\\\\n",
        "\\hat{x}_i &= \\frac{x_i - \\mu_B}{\\sqrt{\\sigma_B^2 + \\epsilon}} \\quad \\text{(normalize)} \\\\\n",
        "y_i &= \\gamma \\hat{x}_i + \\beta \\quad \\text{(scale and shift)}\n",
        "\\end{align}\n",
        "$$\n",
        "\n",
        "где $\\gamma, \\beta$ — learnable parameters.\n",
        "\n",
        "**Преимущества:**\n",
        "- ✅ **Faster training** (можно использовать больший learning rate)\n",
        "- ✅ **Regularization эффект** (меньше нужен dropout)\n",
        "- ✅ **Меньше чувствительность к инициализации**\n",
        "\n",
        "**Где вставлять?**\n",
        "\n",
        "```\n",
        "Linear → BatchNorm → ReLU\n",
        "```\n",
        "\n",
        "(или иногда: Linear → ReLU → BatchNorm)\n",
        "\n",
        "---\n",
        "\n",
        "#### 1.5.4 Early Stopping\n",
        "\n",
        "**Идея:** Остановить обучение, когда validation loss перестает улучшаться.\n",
        "\n",
        "**Алгоритм:**\n",
        "```python\n",
        "best_val_loss = infinity\n",
        "patience_counter = 0\n",
        "\n",
        "for epoch in range(max_epochs):\n",
        "    train(...)\n",
        "    val_loss = validate(...)\n",
        "    \n",
        "    if val_loss < best_val_loss:\n",
        "        best_val_loss = val_loss\n",
        "        save_model()\n",
        "        patience_counter = 0\n",
        "    else:\n",
        "        patience_counter += 1\n",
        "        \n",
        "    if patience_counter >= patience:\n",
        "        break  # Stop training\n",
        "```\n",
        "\n",
        "**Типичные значения:**\n",
        "- `patience = 5-20` epochs\n",
        "\n",
        "---\n",
        "\n",
        "## Теория завершена! Переходим к практике 🚀\n",
        "\n",
        "---"
    ]
})

# Добавляем новые ячейки
for cell in new_cells:
    notebook['cells'].append(cell)

# Сохраняем
with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f'✅ Добавлена теория: {len(new_cells)} ячеек')
print(f'Всего ячеек: {len(notebook["cells"])}')
