#!/usr/bin/env python3
"""
Phase 6: Explainable AI - Part 4
Add: LIME, PDP, Permutation Importance, Fairness Analysis
"""

import json

# Загружаем существующий notebook
notebook_path = '/home/user/test/notebooks/phase6_explainable_ai/01_explainable_ai_xai.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

cells = notebook['cells']

# ============================================================================
# LIME ANALYSIS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 🔬 Часть 3: LIME Analysis\n",
        "\n",
        "### Что такое LIME?\n",
        "\n",
        "**LIME (Local Interpretable Model-agnostic Explanations)** - метод для объяснения **отдельных predictions** любой модели.\n",
        "\n",
        "**Как работает:**\n",
        "1. Берём интересующий нас sample\n",
        "2. Генерируем perturbed samples (слегка изменяем признаки)\n",
        "3. Получаем predictions для них от черного ящика\n",
        "4. Обучаем **простую интерпретируемую модель** (linear/decision tree) локально\n",
        "5. Интерпретируем простую модель\n",
        "\n",
        "**LIME vs SHAP:**\n",
        "\n",
        "| Аспект | LIME | SHAP |\n",
        "|--------|------|------|\n",
        "| Теоретическое обоснование | ❌ Heuristic | ✅ Game theory (Shapley) |\n",
        "| Consistency | ❌ Не гарантируется | ✅ Гарантируется |\n",
        "| Скорость (local) | ✅ Быстрее | ⚠️ KernelSHAP медленнее |\n",
        "| Скорость (tree models) | ⚠️ Медленнее | ✅ TreeSHAP очень быстро |\n",
        "| Stability | ❌ Может варьироваться | ✅ Стабильнее |\n",
        "| Global interpretation | ❌ Нет | ✅ Да |\n",
        "| Use case | Quick local explanations | Production, требуется consistency |\n",
        "\n",
        "**Когда использовать LIME:**\n",
        "- ✅ Быстрые ad-hoc локальные объяснения\n",
        "- ✅ Модели, для которых нет TreeSHAP (custom black boxes)\n",
        "- ✅ Text/Image classification (LIME хорошо работает с ними)\n",
        "- ⚠️ НЕ для production, где важна consistency\n",
        "\n",
        "---\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"=\" * 70)\n",
        "print(\"LIME ANALYSIS\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Создаём LIME explainer\n",
        "print(\"\\nCreating LIME Tabular Explainer...\")\n",
        "lime_explainer = lime.lime_tabular.LimeTabularExplainer(\n",
        "    training_data=X_train_scaled.values,\n",
        "    feature_names=feature_cols,\n",
        "    class_names=['<=50K', '>50K'],\n",
        "    mode='classification',\n",
        "    random_state=42\n",
        ")\n",
        "\n",
        "print(\"✅ LIME explainer created\")\n",
        "\n",
        "# Объясняем тот же high income sample, что и с SHAP\n",
        "high_income_sample = X_test_scaled.iloc[high_income_idx].values\n",
        "\n",
        "print(f\"\\nExplaining sample {high_income_idx} (predicted >50K)...\")\n",
        "lime_exp = lime_explainer.explain_instance(\n",
        "    high_income_sample,\n",
        "    models['Random Forest'].predict_proba,\n",
        "    num_features=10,\n",
        "    num_samples=1000  # сколько perturbed samples генерировать\n",
        ")\n",
        "\n",
        "print(\"✅ LIME explanation computed\")\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Визуализация LIME explanation\n",
        "fig = lime_exp.as_pyplot_figure(label=1)  # label=1 для класса >50K\n",
        "plt.title(f'LIME Explanation: Sample {high_income_idx} (>50K)', fontsize=14, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Текстовое представление\n",
        "print(\"\\n📊 LIME Explanation (Top features):\")\n",
        "print(\"=\"*50)\n",
        "for feature, weight in lime_exp.as_list(label=1)[:10]:\n",
        "    print(f\"{feature:40s} : {weight:+.4f}\")\n",
        "\n",
        "print(\"\\n💡 Интерпретация:\")\n",
        "print(\"- Positive weight → increases P(>50K)\")\n",
        "print(\"- Negative weight → decreases P(>50K)\")\n",
        "print(\"- Величина weight = strength of effect\")\n"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "#### 3.1 Сравнение LIME vs SHAP\n",
        "\n",
        "Сравним объяснения для того же sample."
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Сравнение LIME vs SHAP для одного sample\n",
        "print(\"=\" * 70)\n",
        "print(f\"COMPARISON: LIME vs SHAP (Sample {high_income_idx})\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# LIME feature importances\n",
        "lime_dict = dict(lime_exp.as_list(label=1))\n",
        "lime_values = {}\n",
        "for feature in feature_cols:\n",
        "    # LIME возвращает строки типа \"feature <= value\"\n",
        "    for lime_feature, value in lime_dict.items():\n",
        "        if feature in lime_feature:\n",
        "            lime_values[feature] = value\n",
        "            break\n",
        "    if feature not in lime_values:\n",
        "        lime_values[feature] = 0.0\n",
        "\n",
        "# SHAP values для этого sample\n",
        "shap_dict = dict(zip(feature_cols, rf_shap_values_class1[high_income_idx]))\n",
        "\n",
        "# Создаём сравнительный DataFrame\n",
        "comparison_local = pd.DataFrame({\n",
        "    'Feature': feature_cols,\n",
        "    'LIME': [lime_values.get(f, 0) for f in feature_cols],\n",
        "    'SHAP': [shap_dict[f] for f in feature_cols]\n",
        "})\n",
        "\n",
        "# Сортируем по абсолютному значению SHAP\n",
        "comparison_local['abs_SHAP'] = comparison_local['SHAP'].abs()\n",
        "comparison_local = comparison_local.sort_values('abs_SHAP', ascending=False).head(10)\n",
        "\n",
        "print(\"\\nTop 10 features:\")\n",
        "print(comparison_local[['Feature', 'LIME', 'SHAP']].to_string(index=False))\n",
        "\n",
        "# Визуализация\n",
        "fig, ax = plt.subplots(figsize=(12, 6))\n",
        "\n",
        "x = np.arange(len(comparison_local))\n",
        "width = 0.35\n",
        "\n",
        "ax.barh(x - width/2, comparison_local['LIME'], width, label='LIME', alpha=0.8)\n",
        "ax.barh(x + width/2, comparison_local['SHAP'], width, label='SHAP', alpha=0.8)\n",
        "\n",
        "ax.set_yticks(x)\n",
        "ax.set_yticklabels(comparison_local['Feature'])\n",
        "ax.set_xlabel('Feature Importance (local explanation)', fontsize=12)\n",
        "ax.set_title(f'LIME vs SHAP: Sample {high_income_idx}', fontsize=14, fontweight='bold')\n",
        "ax.legend()\n",
        "ax.invert_yaxis()\n",
        "ax.axvline(x=0, color='black', linestyle='-', linewidth=0.5)\n",
        "ax.grid(axis='x', alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n🔍 Наблюдения:\")\n",
        "print(\"- LIME и SHAP обычно согласны в топовых признаках\")\n",
        "print(\"- Magnitude может отличаться (разные шкалы)\")\n",
        "print(\"- SHAP более стабильный и теоретически обоснованный\")\n",
        "print(\"- LIME быстрее для quick ad-hoc explanations\")\n"
    ]
})

# ============================================================================
# PARTIAL DEPENDENCE PLOTS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 📊 Часть 4: Partial Dependence Plots (PDP)\n",
        "\n",
        "### Что такое PDP?\n",
        "\n",
        "**Partial Dependence Plot** показывает **глобальное влияние** признака на predictions:\n",
        "- Как меняется среднее prediction при изменении признака?\n",
        "- Независимо от других признаков (marginalized)\n",
        "\n",
        "**Как работает:**\n",
        "1. Фиксируем интересующий признак на разных значениях\n",
        "2. Для каждого значения: делаем predictions для всего датасета\n",
        "3. Усредняем predictions\n",
        "4. Строим график: feature value vs average prediction\n",
        "\n",
        "**Преимущества:**\n",
        "- ✅ Global view (не только локальное объяснение)\n",
        "- ✅ Визуально понятно\n",
        "- ✅ Показывает нелинейные эффекты\n",
        "\n",
        "**Ограничения:**\n",
        "- ⚠️ **Assumes independence:** если признаки коррелируют, может вводить в заблуждение\n",
        "- ⚠️ **Averages out heterogeneity:** не показывает индивидуальные вариации\n",
        "\n",
        "**ICE (Individual Conditional Expectation) curves:**\n",
        "- Решает проблему averaging\n",
        "- Показывает зависимость для каждого sample отдельно\n",
        "- PDP = average of ICE curves\n",
        "\n",
        "---\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"=\" * 70)\n",
        "print(\"PARTIAL DEPENDENCE PLOTS (PDP)\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Топ признаки для PDP\n",
        "pdp_features = ['age', 'education-num', 'hours-per-week', 'capital-gain']\n",
        "\n",
        "print(f\"\\nBuilding PDP for: {pdp_features}\")\n",
        "\n",
        "# PDP для Random Forest\n",
        "fig, ax = plt.subplots(figsize=(14, 8))\n",
        "\n",
        "display = PartialDependenceDisplay.from_estimator(\n",
        "    models['Random Forest'],\n",
        "    X_test_scaled.iloc[:500],  # используем подвыборку для скорости\n",
        "    features=pdp_features,\n",
        "    feature_names=feature_cols,\n",
        "    ax=ax,\n",
        "    n_jobs=-1\n",
        ")\n",
        "\n",
        "plt.suptitle('Partial Dependence Plots: Random Forest', fontsize=14, fontweight='bold', y=0.98)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n✅ PDP completed\")\n",
        "print(\"\\n📊 Интерпретация:\")\n",
        "print(\"- age: С возрастом вероятность >50K растёт (до определенного момента)\")\n",
        "print(\"- education-num: Больше образования → выше вероятность >50K\")\n",
        "print(\"- hours-per-week: Больше часов работы → выше income\")\n",
        "print(\"- capital-gain: Наличие capital gain → резко увеличивает вероятность\")\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 2D PDP для взаимодействий\n",
        "print(\"\\n2D Partial Dependence: Feature Interactions\")\n",
        "print(\"=\"*50)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(10, 8))\n",
        "\n",
        "# PDP для взаимодействия age и education-num\n",
        "display_2d = PartialDependenceDisplay.from_estimator(\n",
        "    models['Random Forest'],\n",
        "    X_test_scaled.iloc[:500],\n",
        "    features=[('age', 'education-num')],\n",
        "    feature_names=feature_cols,\n",
        "    ax=ax,\n",
        "    n_jobs=-1\n",
        ")\n",
        "\n",
        "plt.suptitle('2D PDP: Age × Education Interaction', fontsize=14, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n💡 Interaction effect:\")\n",
        "print(\"- Светлые области = высокая вероятность >50K\")\n",
        "print(\"- Тёмные области = низкая вероятность >50K\")\n",
        "print(\"- Видим joint effect возраста и образования\")\n"
    ]
})

# ============================================================================
# PERMUTATION IMPORTANCE
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 4.1 Permutation Importance\n",
        "\n",
        "**Permutation Importance** - простой и эффективный метод для оценки важности признаков:\n",
        "\n",
        "**Алгоритм:**\n",
        "1. Вычисляем baseline metric (accuracy, AUC, etc.) на test set\n",
        "2. Для каждого признака:\n",
        "   - Shuffle значения признака (breaks relationship с target)\n",
        "   - Вычисляем metric заново\n",
        "   - Importance = baseline - shuffled metric\n",
        "3. Repeat несколько раз для стабильности\n",
        "\n",
        "**Преимущества:**\n",
        "- ✅ **Model-agnostic** (работает с любой моделью)\n",
        "- ✅ **Handles correlations** (в отличие от Gini importance)\n",
        "- ✅ **Intuitive interpretation**\n",
        "\n",
        "**vs Gini Importance (Feature Importance в Random Forest):**\n",
        "- Gini importance: сколько признак используется в splits\n",
        "- **Проблема:** bias к high-cardinality features\n",
        "- Permutation Importance: реальное влияние на predictions\n",
        "\n",
        "---\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"=\" * 70)\n",
        "print(\"PERMUTATION IMPORTANCE\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Вычисляем permutation importance для Random Forest\n",
        "print(\"\\nComputing Permutation Importance (это может занять минуту)...\")\n",
        "perm_importance = permutation_importance(\n",
        "    models['Random Forest'],\n",
        "    X_test_scaled.iloc[:1000],\n",
        "    y_test.iloc[:1000],\n",
        "    n_repeats=10,\n",
        "    random_state=42,\n",
        "    n_jobs=-1,\n",
        "    scoring='roc_auc'\n",
        ")\n",
        "\n",
        "print(\"✅ Permutation Importance computed\")\n",
        "\n",
        "# Сортируем признаки по importance\n",
        "perm_sorted_idx = perm_importance.importances_mean.argsort()[::-1]\n",
        "\n",
        "# Создаём DataFrame\n",
        "perm_df = pd.DataFrame({\n",
        "    'Feature': np.array(feature_cols)[perm_sorted_idx],\n",
        "    'Importance': perm_importance.importances_mean[perm_sorted_idx],\n",
        "    'Std': perm_importance.importances_std[perm_sorted_idx]\n",
        "})\n",
        "\n",
        "print(\"\\n📊 Top 10 Features by Permutation Importance:\")\n",
        "print(perm_df.head(10).to_string(index=False))\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Визуализация Permutation Importance\n",
        "fig, ax = plt.subplots(figsize=(10, 8))\n",
        "\n",
        "top_n = 15\n",
        "ax.barh(\n",
        "    range(top_n),\n",
        "    perm_df.head(top_n)['Importance'],\n",
        "    xerr=perm_df.head(top_n)['Std'],\n",
        "    alpha=0.8\n",
        ")\n",
        "\n",
        "ax.set_yticks(range(top_n))\n",
        "ax.set_yticklabels(perm_df.head(top_n)['Feature'])\n",
        "ax.set_xlabel('Importance (decrease in ROC AUC)', fontsize=12)\n",
        "ax.set_title('Permutation Importance: Random Forest', fontsize=14, fontweight='bold')\n",
        "ax.invert_yaxis()\n",
        "ax.grid(axis='x', alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n💡 Интерпретация:\")\n",
        "print(\"- Высокая importance → shuffling признака сильно ухудшает модель\")\n",
        "print(\"- Error bars показывают variance (стабильность)\")\n",
        "print(\"- Отрицательная importance → признак не помогает (шум)\")\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Сравнение Gini vs Permutation Importance\n",
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"COMPARISON: Gini Importance vs Permutation Importance\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Gini importance (встроенная в Random Forest)\n",
        "gini_importance = models['Random Forest'].feature_importances_\n",
        "\n",
        "# Создаём сравнительный DataFrame\n",
        "importance_comparison = pd.DataFrame({\n",
        "    'Feature': feature_cols,\n",
        "    'Gini': gini_importance,\n",
        "    'Permutation': perm_importance.importances_mean\n",
        "}).sort_values('Permutation', ascending=False)\n",
        "\n",
        "# Визуализация\n",
        "fig, ax = plt.subplots(figsize=(12, 8))\n",
        "\n",
        "x = np.arange(12)\n",
        "width = 0.35\n",
        "\n",
        "ax.barh(x - width/2, importance_comparison.head(12)['Gini'], width, label='Gini (MDI)', alpha=0.8)\n",
        "ax.barh(x + width/2, importance_comparison.head(12)['Permutation'], width, label='Permutation', alpha=0.8)\n",
        "\n",
        "ax.set_yticks(x)\n",
        "ax.set_yticklabels(importance_comparison.head(12)['Feature'])\n",
        "ax.set_xlabel('Importance', fontsize=12)\n",
        "ax.set_title('Gini vs Permutation Importance', fontsize=14, fontweight='bold')\n",
        "ax.legend()\n",
        "ax.invert_yaxis()\n",
        "ax.grid(axis='x', alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n🔍 Наблюдения:\")\n",
        "print(\"- Gini и Permutation обычно согласны в топовых признаках\")\n",
        "print(\"- Gini может переоценивать high-cardinality features\")\n",
        "print(\"- Permutation более надёжный для feature selection\")\n",
        "print(\"- SHAP > Permutation > Gini (в плане теоретической обоснованности)\")\n"
    ]
})

# ============================================================================
# FAIRNESS ANALYSIS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## ⚖️ Часть 5: Fairness Analysis\n",
        "\n",
        "### Почему Fairness важен?\n",
        "\n",
        "**Проблема:** Высокая accuracy ≠ справедливая модель\n",
        "\n",
        "**Real-world примеры bias:**\n",
        "- **Amazon Recruiting AI (2018):** модель дискриминировала женщин (обучалась на исторических данных с bias)\n",
        "- **COMPAS (Criminal Justice):** алгоритм предсказания recidivism показывал racial bias\n",
        "- **Credit Scoring:** модели могут дискриминировать по возрасту, полу, расе\n",
        "- **Healthcare:** алгоритмы могут хуже работать для minority groups\n",
        "\n",
        "**Законодательные требования:**\n",
        "- 🇺🇸 **Equal Credit Opportunity Act** - запрещает дискриминацию в кредитовании\n",
        "- 🇪🇺 **GDPR Article 22** - право на объяснение автоматизированных решений\n",
        "- 🇺🇸 **Fair Housing Act** - fairness в жилищном кредитовании\n",
        "\n",
        "### Типы Fairness Metrics:\n",
        "\n",
        "#### 1. **Demographic Parity (Statistical Parity)**\n",
        "```\n",
        "P(Y_pred = 1 | Sex = Male) = P(Y_pred = 1 | Sex = Female)\n",
        "```\n",
        "- Одинаковая доля positive predictions в каждой группе\n",
        "- **Проблема:** игнорирует базовые различия в ground truth\n",
        "\n",
        "#### 2. **Equal Opportunity**\n",
        "```\n",
        "P(Y_pred = 1 | Y_true = 1, Sex = Male) = P(Y_pred = 1 | Y_true = 1, Sex = Female)\n",
        "```\n",
        "- Одинаковый True Positive Rate для всех групп\n",
        "- **Лучше:** учитывает ground truth\n",
        "\n",
        "#### 3. **Equalized Odds**\n",
        "```\n",
        "Equal Opportunity + Equal False Positive Rate\n",
        "```\n",
        "- И TPR, и FPR одинаковые для всех групп\n",
        "\n",
        "#### 4. **Calibration**\n",
        "```\n",
        "P(Y_true = 1 | Y_pred_proba = p, Sex = Male) = P(Y_true = 1 | Y_pred_proba = p, Sex = Female)\n",
        "```\n",
        "- Predicted probabilities соответствуют реальным для всех групп\n",
        "\n",
        "**Trade-offs:**\n",
        "- ⚠️ **Невозможно** удовлетворить все fairness criteria одновременно (теорема impossibility)\n",
        "- ⚠️ **Fairness vs Accuracy trade-off** - иногда нужно жертвовать accuracy\n",
        "\n",
        "---\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"=\" * 70)\n",
        "print(\"FAIRNESS ANALYSIS\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Анализируем fairness по полу (sensitive attribute)\n",
        "print(\"\\nAnalyzing fairness by SEX...\")\n",
        "\n",
        "# Predictions для test set\n",
        "rf_predictions = results['Random Forest']['predictions']\n",
        "rf_probabilities = results['Random Forest']['probabilities']\n",
        "\n",
        "# Добавляем predictions к sensitive attributes\n",
        "fairness_df = sensitive_test.copy()\n",
        "fairness_df['y_true'] = y_test.values\n",
        "fairness_df['y_pred'] = rf_predictions\n",
        "fairness_df['y_prob'] = rf_probabilities\n",
        "\n",
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"1. DEMOGRAPHIC PARITY (Statistical Parity)\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Demographic Parity: доля positive predictions по группам\n",
        "demo_parity = fairness_df.groupby('sex')['y_pred'].mean()\n",
        "print(\"\\nP(Y_pred = 1 | Sex):\")\n",
        "for sex, prob in demo_parity.items():\n",
        "    print(f\"  {sex:10s}: {prob:.4f} ({prob*100:.2f}%)\")\n",
        "\n",
        "# Disparate Impact Ratio\n",
        "female_rate = demo_parity.get('Female', demo_parity.iloc[0])\n",
        "male_rate = demo_parity.get('Male', demo_parity.iloc[1])\n",
        "disparate_impact = female_rate / male_rate if male_rate > 0 else 0\n",
        "\n",
        "print(f\"\\nDisparate Impact Ratio: {disparate_impact:.4f}\")\n",
        "print(\"  (Female rate / Male rate)\")\n",
        "print(\"  ✅ Good if between 0.8 and 1.25 (80% rule)\")\n",
        "if 0.8 <= disparate_impact <= 1.25:\n",
        "    print(\"  ✅ PASS: Demographic Parity satisfied\")\n",
        "else:\n",
        "    print(f\"  ⚠️ FAIL: Potential bias (ratio = {disparate_impact:.2f})\")\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"2. EQUAL OPPORTUNITY (True Positive Rate)\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Equal Opportunity: TPR по группам (среди тех, кто действительно >50K)\n",
        "positive_class = fairness_df[fairness_df['y_true'] == 1]\n",
        "tpr_by_sex = positive_class.groupby('sex')['y_pred'].mean()\n",
        "\n",
        "print(\"\\nTrue Positive Rate (Recall) by Sex:\")\n",
        "for sex, tpr in tpr_by_sex.items():\n",
        "    print(f\"  {sex:10s}: {tpr:.4f} ({tpr*100:.2f}%)\")\n",
        "\n",
        "# Difference in TPR\n",
        "tpr_diff = abs(tpr_by_sex.iloc[0] - tpr_by_sex.iloc[1])\n",
        "print(f\"\\nDifference in TPR: {tpr_diff:.4f}\")\n",
        "if tpr_diff < 0.05:\n",
        "    print(\"  ✅ PASS: Equal Opportunity satisfied (diff < 5%)\")\n",
        "else:\n",
        "    print(f\"  ⚠️ WARNING: TPR differs by {tpr_diff*100:.1f}%\")\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"3. FALSE POSITIVE RATE (FPR) BY SEX\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# FPR по группам (среди тех, кто действительно <=50K)\n",
        "negative_class = fairness_df[fairness_df['y_true'] == 0]\n",
        "fpr_by_sex = negative_class.groupby('sex')['y_pred'].mean()\n",
        "\n",
        "print(\"\\nFalse Positive Rate by Sex:\")\n",
        "for sex, fpr in fpr_by_sex.items():\n",
        "    print(f\"  {sex:10s}: {fpr:.4f} ({fpr*100:.2f}%)\")\n",
        "\n",
        "# Difference in FPR\n",
        "fpr_diff = abs(fpr_by_sex.iloc[0] - fpr_by_sex.iloc[1])\n",
        "print(f\"\\nDifference in FPR: {fpr_diff:.4f}\")\n",
        "if fpr_diff < 0.05:\n",
        "    print(\"  ✅ PASS: FPR similar across groups (diff < 5%)\")\n",
        "else:\n",
        "    print(f\"  ⚠️ WARNING: FPR differs by {fpr_diff*100:.1f}%\")\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Визуализация fairness metrics\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# 1. Demographic Parity\n",
        "demo_parity.plot(kind='bar', ax=axes[0, 0], color=['#e74c3c', '#3498db'])\n",
        "axes[0, 0].set_title('Demographic Parity: P(Y_pred=1 | Sex)', fontsize=12, fontweight='bold')\n",
        "axes[0, 0].set_ylabel('Positive Prediction Rate')\n",
        "axes[0, 0].set_xlabel('Sex')\n",
        "axes[0, 0].tick_params(axis='x', rotation=0)\n",
        "axes[0, 0].axhline(y=demo_parity.mean(), color='green', linestyle='--', label='Overall mean')\n",
        "axes[0, 0].legend()\n",
        "axes[0, 0].grid(axis='y', alpha=0.3)\n",
        "\n",
        "# 2. True Positive Rate\n",
        "tpr_by_sex.plot(kind='bar', ax=axes[0, 1], color=['#e74c3c', '#3498db'])\n",
        "axes[0, 1].set_title('Equal Opportunity: TPR by Sex', fontsize=12, fontweight='bold')\n",
        "axes[0, 1].set_ylabel('True Positive Rate')\n",
        "axes[0, 1].set_xlabel('Sex')\n",
        "axes[0, 1].tick_params(axis='x', rotation=0)\n",
        "axes[0, 1].axhline(y=tpr_by_sex.mean(), color='green', linestyle='--', label='Overall mean')\n",
        "axes[0, 1].legend()\n",
        "axes[0, 1].grid(axis='y', alpha=0.3)\n",
        "\n",
        "# 3. False Positive Rate\n",
        "fpr_by_sex.plot(kind='bar', ax=axes[1, 0], color=['#e74c3c', '#3498db'])\n",
        "axes[1, 0].set_title('FPR by Sex', fontsize=12, fontweight='bold')\n",
        "axes[1, 0].set_ylabel('False Positive Rate')\n",
        "axes[1, 0].set_xlabel('Sex')\n",
        "axes[1, 0].tick_params(axis='x', rotation=0)\n",
        "axes[1, 0].axhline(y=fpr_by_sex.mean(), color='green', linestyle='--', label='Overall mean')\n",
        "axes[1, 0].legend()\n",
        "axes[1, 0].grid(axis='y', alpha=0.3)\n",
        "\n",
        "# 4. Confusion Matrix by Sex\n",
        "from sklearn.metrics import confusion_matrix\n",
        "\n",
        "# Aggregate metrics для визуализации\n",
        "metrics_by_sex = {}\n",
        "for sex in fairness_df['sex'].unique():\n",
        "    sex_data = fairness_df[fairness_df['sex'] == sex]\n",
        "    metrics_by_sex[sex] = {\n",
        "        'Accuracy': accuracy_score(sex_data['y_true'], sex_data['y_pred']),\n",
        "        'Precision': precision_score(sex_data['y_true'], sex_data['y_pred']),\n",
        "        'Recall': recall_score(sex_data['y_true'], sex_data['y_pred']),\n",
        "        'F1': f1_score(sex_data['y_true'], sex_data['y_pred'])\n",
        "    }\n",
        "\n",
        "metrics_df = pd.DataFrame(metrics_by_sex).T\n",
        "metrics_df.plot(kind='bar', ax=axes[1, 1], width=0.8)\n",
        "axes[1, 1].set_title('Performance Metrics by Sex', fontsize=12, fontweight='bold')\n",
        "axes[1, 1].set_ylabel('Score')\n",
        "axes[1, 1].set_xlabel('Sex')\n",
        "axes[1, 1].tick_params(axis='x', rotation=0)\n",
        "axes[1, 1].legend(loc='lower right')\n",
        "axes[1, 1].grid(axis='y', alpha=0.3)\n",
        "\n",
        "plt.suptitle('Fairness Analysis: Sex-based Metrics', fontsize=14, fontweight='bold', y=1.00)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n📊 Summary Table:\")\n",
        "print(metrics_df.round(4))\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Calibration Analysis\n",
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"4. CALIBRATION ANALYSIS\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# Calibration curves по группам\n",
        "from sklearn.calibration import calibration_curve\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(10, 8))\n",
        "\n",
        "for sex in fairness_df['sex'].unique():\n",
        "    sex_data = fairness_df[fairness_df['sex'] == sex]\n",
        "    \n",
        "    fraction_of_positives, mean_predicted_value = calibration_curve(\n",
        "        sex_data['y_true'],\n",
        "        sex_data['y_prob'],\n",
        "        n_bins=10,\n",
        "        strategy='uniform'\n",
        "    )\n",
        "    \n",
        "    ax.plot(\n",
        "        mean_predicted_value,\n",
        "        fraction_of_positives,\n",
        "        marker='o',\n",
        "        linewidth=2,\n",
        "        label=sex\n",
        "    )\n",
        "\n",
        "# Perfect calibration line\n",
        "ax.plot([0, 1], [0, 1], 'k--', label='Perfect Calibration')\n",
        "\n",
        "ax.set_xlabel('Mean Predicted Probability', fontsize=12)\n",
        "ax.set_ylabel('Fraction of Positives', fontsize=12)\n",
        "ax.set_title('Calibration Curve by Sex', fontsize=14, fontweight='bold')\n",
        "ax.legend()\n",
        "ax.grid(alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n💡 Интерпретация Calibration:\")\n",
        "print(\"- Линия близка к diagonal → модель well-calibrated\")\n",
        "print(\"- Above diagonal → модель underestimates probabilities\")\n",
        "print(\"- Below diagonal → модель overestimates probabilities\")\n",
        "print(\"- Если кривые для разных групп различаются → calibration bias\")\n"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 5.1 Bias Mitigation Strategies\n",
        "\n",
        "Если обнаружен bias, что делать?\n",
        "\n",
        "#### 1. **Pre-processing** (до обучения модели)\n",
        "- **Reweighting:** давать больший вес underrepresented groups\n",
        "- **Resampling:** oversample minority, undersample majority\n",
        "- **Data augmentation:** генерировать синтетические примеры\n",
        "- **Feature removal:** удалить sensitive attributes (но осторожно - может не помочь из-за proxy features)\n",
        "\n",
        "#### 2. **In-processing** (во время обучения)\n",
        "- **Fairness constraints:** добавить fairness penalty в loss function\n",
        "- **Adversarial debiasing:** обучить adversarial network, чтобы predictions не зависели от sensitive attribute\n",
        "- **Fair representations:** learn embedding, где sensitive info удалена\n",
        "\n",
        "#### 3. **Post-processing** (после обучения)\n",
        "- **Threshold optimization:** разные thresholds для разных групп\n",
        "- **Calibration:** recalibrate probabilities per group\n",
        "- **Reject option:** не делать prediction, если confidence низкая\n",
        "\n",
        "**Trade-offs:**\n",
        "- ⚠️ **Fairness vs Accuracy:** mitigation может снизить overall accuracy\n",
        "- ⚠️ **Which fairness metric?** невозможно удовлетворить все одновременно\n",
        "- ⚠️ **Legal considerations:** некоторые методы (e.g., different thresholds) могут быть illegal\n",
        "\n",
        "**Best practices:**\n",
        "1. ✅ **Measure fairness** на test set для всех sensitive groups\n",
        "2. ✅ **Document** bias analysis и mitigation efforts (model cards)\n",
        "3. ✅ **Monitor** fairness in production (drift)\n",
        "4. ✅ **Stakeholder involvement:** involve affected communities\n",
        "5. ✅ **Transparency:** объяснять decisions, особенно для high-stakes applications\n",
        "\n",
        "---\n"
    ]
})

# Сохраняем обновленный notebook
notebook['cells'] = cells

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f'\\n✅ Updated notebook: {notebook_path}')
print(f'Total cells: {len(cells)}')
print('LIME, PDP, Permutation Importance, and Fairness Analysis added!')
