#!/usr/bin/env python3
"""
Phase 7: Production & MLOps - Part 4 (Final)
CI/CD, DVC, Conclusions
"""

import json

# Загружаем существующий notebook
notebook_path = '/home/user/test/notebooks/phase7_production_mlops/01_production_mlops.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

cells = notebook['cells']

# ============================================================================
# CI/CD FOR ML
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 🔄 Часть 7: CI/CD для ML\n",
        "\n",
        "### Почему CI/CD для ML отличается от обычного?\n",
        "\n",
        "**Обычный CI/CD:**\n",
        "```\n",
        "Code → Build → Test → Deploy\n",
        "```\n",
        "\n",
        "**ML CI/CD:**\n",
        "```\n",
        "Data → Feature Engineering → Train → Validate → Test → Package → Deploy → Monitor\n",
        "```\n",
        "\n",
        "**Дополнительные challenges:**\n",
        "- ✅ **Data validation:** Проверка качества данных\n",
        "- ✅ **Model validation:** Проверка качества модели\n",
        "- ✅ **Feature validation:** Проверка feature distributions\n",
        "- ✅ **Performance regression:** Модель не должна деградировать\n",
        "- ✅ **A/B testing:** Сравнение с production моделью\n",
        "\n",
        "### GitHub Actions для ML\n",
        "\n",
        "**Workflow stages:**\n",
        "\n",
        "1. **On Push/PR:**\n",
        "   - Lint code (flake8, black)\n",
        "   - Run unit tests\n",
        "   - Run integration tests\n",
        "   - Validate data schema\n",
        "\n",
        "2. **On Model Training:**\n",
        "   - Train model\n",
        "   - Validate model metrics\n",
        "   - Compare with baseline\n",
        "   - Register model (if better)\n",
        "\n",
        "3. **On Deploy:**\n",
        "   - Build Docker image\n",
        "   - Push to registry\n",
        "   - Deploy to staging\n",
        "   - Run smoke tests\n",
        "   - Deploy to production\n",
        "\n",
        "---\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# GitHub Actions Workflow\n",
        "github_actions_workflow = '''name: ML Pipeline CI/CD\n",
        "\n",
        "on:\n",
        "  push:\n",
        "    branches: [main, develop]\n",
        "  pull_request:\n",
        "    branches: [main]\n",
        "  workflow_dispatch:  # Manual trigger\n",
        "\n",
        "env:\n",
        "  PYTHON_VERSION: \"3.9\"\n",
        "  MODEL_NAME: \"churn-predictor\"\n",
        "\n",
        "jobs:\n",
        "  # ========================================\n",
        "  # Stage 1: Code Quality\n",
        "  # ========================================\n",
        "  lint-and-test:\n",
        "    name: Lint and Test\n",
        "    runs-on: ubuntu-latest\n",
        "    \n",
        "    steps:\n",
        "      - name: Checkout code\n",
        "        uses: actions/checkout@v3\n",
        "        \n",
        "      - name: Set up Python\n",
        "        uses: actions/setup-python@v4\n",
        "        with:\n",
        "          python-version: ${{ env.PYTHON_VERSION }}\n",
        "          \n",
        "      - name: Cache pip dependencies\n",
        "        uses: actions/cache@v3\n",
        "        with:\n",
        "          path: ~/.cache/pip\n",
        "          key: ${{ runner.os }}-pip-${{ hashFiles(\"requirements.txt\") }}\n",
        "          \n",
        "      - name: Install dependencies\n",
        "        run: |\n",
        "          pip install --upgrade pip\n",
        "          pip install -r requirements.txt\n",
        "          pip install pytest pytest-cov flake8 black\n",
        "          \n",
        "      - name: Lint with flake8\n",
        "        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics\n",
        "        \n",
        "      - name: Check formatting with black\n",
        "        run: black --check .\n",
        "        \n",
        "      - name: Run unit tests\n",
        "        run: pytest tests/unit/ -v --cov=src --cov-report=xml\n",
        "        \n",
        "      - name: Upload coverage\n",
        "        uses: codecov/codecov-action@v3\n",
        "        with:\n",
        "          file: ./coverage.xml\n",
        "\n",
        "  # ========================================\n",
        "  # Stage 2: Data Validation\n",
        "  # ========================================\n",
        "  data-validation:\n",
        "    name: Validate Data\n",
        "    runs-on: ubuntu-latest\n",
        "    needs: lint-and-test\n",
        "    \n",
        "    steps:\n",
        "      - name: Checkout code\n",
        "        uses: actions/checkout@v3\n",
        "        \n",
        "      - name: Set up Python\n",
        "        uses: actions/setup-python@v4\n",
        "        with:\n",
        "          python-version: ${{ env.PYTHON_VERSION }}\n",
        "          \n",
        "      - name: Install dependencies\n",
        "        run: pip install -r requirements.txt\n",
        "        \n",
        "      - name: Validate data schema\n",
        "        run: python scripts/validate_data.py\n",
        "        \n",
        "      - name: Check for data drift\n",
        "        run: python scripts/check_drift.py\n",
        "\n",
        "  # ========================================\n",
        "  # Stage 3: Model Training\n",
        "  # ========================================\n",
        "  train-model:\n",
        "    name: Train Model\n",
        "    runs-on: ubuntu-latest\n",
        "    needs: data-validation\n",
        "    if: github.event_name == \"push\" && github.ref == \"refs/heads/main\"\n",
        "    \n",
        "    steps:\n",
        "      - name: Checkout code\n",
        "        uses: actions/checkout@v3\n",
        "        \n",
        "      - name: Set up Python\n",
        "        uses: actions/setup-python@v4\n",
        "        with:\n",
        "          python-version: ${{ env.PYTHON_VERSION }}\n",
        "          \n",
        "      - name: Install dependencies\n",
        "        run: pip install -r requirements.txt\n",
        "        \n",
        "      - name: Train model\n",
        "        run: python scripts/train.py\n",
        "        env:\n",
        "          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}\n",
        "          \n",
        "      - name: Validate model performance\n",
        "        run: python scripts/validate_model.py\n",
        "        \n",
        "      - name: Upload model artifact\n",
        "        uses: actions/upload-artifact@v3\n",
        "        with:\n",
        "          name: model\n",
        "          path: models/\n",
        "\n",
        "  # ========================================\n",
        "  # Stage 4: Build and Push Docker Image\n",
        "  # ========================================\n",
        "  build-docker:\n",
        "    name: Build Docker Image\n",
        "    runs-on: ubuntu-latest\n",
        "    needs: train-model\n",
        "    \n",
        "    steps:\n",
        "      - name: Checkout code\n",
        "        uses: actions/checkout@v3\n",
        "        \n",
        "      - name: Download model artifact\n",
        "        uses: actions/download-artifact@v3\n",
        "        with:\n",
        "          name: model\n",
        "          path: models/\n",
        "          \n",
        "      - name: Set up Docker Buildx\n",
        "        uses: docker/setup-buildx-action@v2\n",
        "        \n",
        "      - name: Login to Docker Hub\n",
        "        uses: docker/login-action@v2\n",
        "        with:\n",
        "          username: ${{ secrets.DOCKER_USERNAME }}\n",
        "          password: ${{ secrets.DOCKER_PASSWORD }}\n",
        "          \n",
        "      - name: Build and push\n",
        "        uses: docker/build-push-action@v4\n",
        "        with:\n",
        "          context: .\n",
        "          push: true\n",
        "          tags: |\n",
        "            ${{ secrets.DOCKER_USERNAME }}/${{ env.MODEL_NAME }}:latest\n",
        "            ${{ secrets.DOCKER_USERNAME }}/${{ env.MODEL_NAME }}:${{ github.sha }}\n",
        "          cache-from: type=gha\n",
        "          cache-to: type=gha,mode=max\n",
        "\n",
        "  # ========================================\n",
        "  # Stage 5: Deploy to Staging\n",
        "  # ========================================\n",
        "  deploy-staging:\n",
        "    name: Deploy to Staging\n",
        "    runs-on: ubuntu-latest\n",
        "    needs: build-docker\n",
        "    environment: staging\n",
        "    \n",
        "    steps:\n",
        "      - name: Deploy to staging\n",
        "        run: |\n",
        "          echo \"Deploying to staging environment...\"\n",
        "          # kubectl set image deployment/$MODEL_NAME ...\n",
        "          # or: aws ecs update-service ...\n",
        "          \n",
        "      - name: Run smoke tests\n",
        "        run: |\n",
        "          echo \"Running smoke tests...\"\n",
        "          # curl -X POST https://staging.api.com/predict ...\n",
        "          \n",
        "      - name: Notify on success\n",
        "        run: echo \"Staging deployment successful!\"\n",
        "\n",
        "  # ========================================\n",
        "  # Stage 6: Deploy to Production\n",
        "  # ========================================\n",
        "  deploy-production:\n",
        "    name: Deploy to Production\n",
        "    runs-on: ubuntu-latest\n",
        "    needs: deploy-staging\n",
        "    environment: production\n",
        "    \n",
        "    steps:\n",
        "      - name: Deploy to production\n",
        "        run: |\n",
        "          echo \"Deploying to production environment...\"\n",
        "          \n",
        "      - name: Notify team\n",
        "        run: echo \"Production deployment complete!\"\n",
        "'''\n",
        "\n",
        "# Save workflow\n",
        "import os\n",
        "os.makedirs('.github/workflows', exist_ok=True)\n",
        "with open('.github/workflows/ml-pipeline.yml', 'w') as f:\n",
        "    f.write(github_actions_workflow)\n",
        "\n",
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"GITHUB ACTIONS CI/CD WORKFLOW\")\n",
        "print(\"=\" * 70)\n",
        "print(\"\\n✅ Workflow saved to: .github/workflows/ml-pipeline.yml\")\n",
        "print(\"\\nStages:\")\n",
        "print(\"  1. lint-and-test      - Code quality checks\")\n",
        "print(\"  2. data-validation    - Data schema and drift\")\n",
        "print(\"  3. train-model        - Model training with MLflow\")\n",
        "print(\"  4. build-docker       - Build and push Docker image\")\n",
        "print(\"  5. deploy-staging     - Deploy to staging + smoke tests\")\n",
        "print(\"  6. deploy-production  - Deploy to production\")\n"
    ]
})

# ============================================================================
# DVC (Data Version Control)
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 📁 Часть 8: Data Version Control (DVC)\n",
        "\n",
        "### Проблема версионирования данных\n",
        "\n",
        "**Git не подходит для данных:**\n",
        "- ❌ Large files (GB, TB)\n",
        "- ❌ Binary files (не видно diff)\n",
        "- ❌ Repository bloat\n",
        "\n",
        "**DVC решает:**\n",
        "- ✅ Git-like workflow для данных\n",
        "- ✅ Remote storage (S3, GCS, Azure Blob)\n",
        "- ✅ Reproducibility\n",
        "- ✅ Pipeline management\n",
        "\n",
        "### Как работает DVC:\n",
        "\n",
        "```\n",
        "┌─────────────┐     ┌─────────────┐\n",
        "│   Git       │     │   DVC       │\n",
        "│   (code)    │     │   (data)    │\n",
        "├─────────────┤     ├─────────────┤\n",
        "│ - app.py    │     │ - data.csv  │\n",
        "│ - train.py  │     │ - model.pkl │\n",
        "│ - data.dvc  │ ←─→ │             │\n",
        "└─────────────┘     └─────────────┘\n",
        "       │                   │\n",
        "       ↓                   ↓\n",
        "   GitHub/GitLab      S3/GCS/Azure\n",
        "```\n",
        "\n",
        "---\n"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"\\n\" + \"=\" * 70)\n",
        "print(\"DVC (DATA VERSION CONTROL)\")\n",
        "print(\"=\" * 70)\n",
        "\n",
        "# DVC commands reference\n",
        "dvc_commands = '''\n",
        "# ========================================\n",
        "# DVC Quick Reference\n",
        "# ========================================\n",
        "\n",
        "# Initialize DVC in project\n",
        "dvc init\n",
        "\n",
        "# Add remote storage (e.g., S3)\n",
        "dvc remote add -d myremote s3://mybucket/dvc-store\n",
        "\n",
        "# Track data files\n",
        "dvc add data/raw/customers.csv\n",
        "dvc add models/churn_predictor.joblib\n",
        "\n",
        "# This creates:\n",
        "# - data/raw/customers.csv.dvc (metadata, tracked by Git)\n",
        "# - .gitignore (добавляет customers.csv)\n",
        "\n",
        "# Commit metadata to Git\n",
        "git add data/raw/customers.csv.dvc data/raw/.gitignore\n",
        "git commit -m \"Add raw customer data\"\n",
        "\n",
        "# Push data to remote storage\n",
        "dvc push\n",
        "\n",
        "# Pull data from remote\n",
        "dvc pull\n",
        "\n",
        "# ========================================\n",
        "# DVC Pipelines\n",
        "# ========================================\n",
        "\n",
        "# Define pipeline in dvc.yaml:\n",
        "# stages:\n",
        "#   preprocess:\n",
        "#     cmd: python src/preprocess.py\n",
        "#     deps:\n",
        "#       - data/raw/customers.csv\n",
        "#       - src/preprocess.py\n",
        "#     outs:\n",
        "#       - data/processed/customers_clean.csv\n",
        "#\n",
        "#   train:\n",
        "#     cmd: python src/train.py\n",
        "#     deps:\n",
        "#       - data/processed/customers_clean.csv\n",
        "#       - src/train.py\n",
        "#     outs:\n",
        "#       - models/churn_predictor.joblib\n",
        "#     metrics:\n",
        "#       - metrics/scores.json\n",
        "\n",
        "# Run pipeline\n",
        "dvc repro\n",
        "\n",
        "# Show pipeline DAG\n",
        "dvc dag\n",
        "\n",
        "# Compare metrics across experiments\n",
        "dvc metrics show\n",
        "dvc metrics diff\n",
        "\n",
        "# ========================================\n",
        "# Version switching\n",
        "# ========================================\n",
        "\n",
        "# Go back to specific version\n",
        "git checkout v1.0\n",
        "dvc checkout\n",
        "\n",
        "# Compare data versions\n",
        "dvc diff HEAD~1\n",
        "'''\n",
        "\n",
        "print(dvc_commands)\n",
        "\n",
        "# Create dvc.yaml example\n",
        "dvc_yaml = '''stages:\n",
        "  preprocess:\n",
        "    cmd: python src/preprocess.py\n",
        "    deps:\n",
        "      - data/raw/customers.csv\n",
        "      - src/preprocess.py\n",
        "    params:\n",
        "      - preprocess.test_size\n",
        "      - preprocess.random_state\n",
        "    outs:\n",
        "      - data/processed/X_train.csv\n",
        "      - data/processed/X_test.csv\n",
        "      - data/processed/y_train.csv\n",
        "      - data/processed/y_test.csv\n",
        "\n",
        "  train:\n",
        "    cmd: python src/train.py\n",
        "    deps:\n",
        "      - data/processed/X_train.csv\n",
        "      - data/processed/y_train.csv\n",
        "      - src/train.py\n",
        "    params:\n",
        "      - train.n_estimators\n",
        "      - train.max_depth\n",
        "      - train.learning_rate\n",
        "    outs:\n",
        "      - models/churn_predictor.joblib\n",
        "      - models/scaler.joblib\n",
        "    metrics:\n",
        "      - metrics/train_metrics.json:\n",
        "          cache: false\n",
        "\n",
        "  evaluate:\n",
        "    cmd: python src/evaluate.py\n",
        "    deps:\n",
        "      - data/processed/X_test.csv\n",
        "      - data/processed/y_test.csv\n",
        "      - models/churn_predictor.joblib\n",
        "      - src/evaluate.py\n",
        "    metrics:\n",
        "      - metrics/eval_metrics.json:\n",
        "          cache: false\n",
        "    plots:\n",
        "      - plots/confusion_matrix.png\n",
        "      - plots/roc_curve.png\n",
        "'''\n",
        "\n",
        "with open('./dvc.yaml', 'w') as f:\n",
        "    f.write(dvc_yaml)\n",
        "\n",
        "print(\"\\n✅ dvc.yaml saved\")\n",
        "print(\"\\nDVC Pipeline Stages:\")\n",
        "print(\"  1. preprocess → Train/test split, scaling\")\n",
        "print(\"  2. train      → Model training\")\n",
        "print(\"  3. evaluate   → Model evaluation, plots\")\n"
    ]
})

# ============================================================================
# CONCLUSIONS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 📋 Часть 9: Summary & Best Practices\n",
        "\n",
        "### Production ML Checklist\n",
        "\n",
        "#### ✅ **Experiment Tracking**\n",
        "- [ ] MLflow/W&B setup для logging\n",
        "- [ ] Parameters, metrics, artifacts logged\n",
        "- [ ] Model Registry configured\n",
        "- [ ] Experiment comparison UI\n",
        "\n",
        "#### ✅ **Model Serialization**\n",
        "- [ ] Model saved (joblib/pickle/ONNX)\n",
        "- [ ] Preprocessing artifacts saved (scaler, encoders)\n",
        "- [ ] Config file with feature columns\n",
        "- [ ] Version metadata\n",
        "\n",
        "#### ✅ **API Development**\n",
        "- [ ] FastAPI/Flask application\n",
        "- [ ] Pydantic schemas for validation\n",
        "- [ ] Health check endpoint\n",
        "- [ ] Error handling\n",
        "- [ ] API documentation (Swagger)\n",
        "- [ ] Rate limiting\n",
        "- [ ] Authentication\n",
        "\n",
        "#### ✅ **Containerization**\n",
        "- [ ] Dockerfile (multi-stage)\n",
        "- [ ] Non-root user\n",
        "- [ ] Health check\n",
        "- [ ] docker-compose.yml\n",
        "- [ ] .dockerignore\n",
        "\n",
        "#### ✅ **Monitoring**\n",
        "- [ ] Data drift detection\n",
        "- [ ] Model performance monitoring\n",
        "- [ ] Prediction distribution tracking\n",
        "- [ ] Latency monitoring\n",
        "- [ ] Alerting setup\n",
        "- [ ] Dashboard (Grafana)\n",
        "\n",
        "#### ✅ **CI/CD**\n",
        "- [ ] GitHub Actions workflow\n",
        "- [ ] Unit tests\n",
        "- [ ] Integration tests\n",
        "- [ ] Data validation\n",
        "- [ ] Model validation\n",
        "- [ ] Automated deployment\n",
        "\n",
        "#### ✅ **Data Versioning**\n",
        "- [ ] DVC initialized\n",
        "- [ ] Remote storage configured\n",
        "- [ ] Data tracked\n",
        "- [ ] Pipeline defined\n",
        "\n",
        "---\n",
        "\n",
        "### 🎯 Key Takeaways\n",
        "\n",
        "#### 1. **Model в Jupyter - это 10% работы**\n",
        "- Остальные 90% - это MLOps\n",
        "- Deployment, monitoring, retraining\n",
        "- Это отличает Data Scientist от ML Engineer\n",
        "\n",
        "#### 2. **Reproducibility is King**\n",
        "- MLflow для experiments\n",
        "- DVC для данных\n",
        "- Docker для environment\n",
        "- Всё должно быть воспроизводимо!\n",
        "\n",
        "#### 3. **Monitoring предотвращает катастрофы**\n",
        "- ML модели деградируют со временем\n",
        "- Data drift, concept drift, model drift\n",
        "- Мониторинг → раннее обнаружение → быстрая реакция\n",
        "\n",
        "#### 4. **Automation снижает риски**\n",
        "- Manual deployments → ошибки\n",
        "- CI/CD → consistent, reliable deployments\n",
        "- Automated testing → catches bugs early\n",
        "\n",
        "#### 5. **Start Simple, Iterate**\n",
        "- Не нужен Kubernetes с первого дня\n",
        "- Начните с Docker + простой CI/CD\n",
        "- Добавляйте complexity по мере необходимости\n",
        "\n",
        "---\n",
        "\n",
        "### 🔗 Связь с предыдущими фазами\n",
        "\n",
        "**Phase 7 использует все предыдущие знания:**\n",
        "\n",
        "- **Phase 1-3:** Модели для deployment (RF, XGBoost, etc.)\n",
        "- **Phase 4:** Transformers для сложных задач\n",
        "- **Phase 5:** Anomaly detection для monitoring\n",
        "- **Phase 6:** SHAP для explainability в production\n",
        "\n",
        "**Phase 7 завершает цикл:**\n",
        "\n",
        "```\n",
        "Research → Development → Production → Monitoring → Research...\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "### 📚 Tools Reference\n",
        "\n",
        "| Category | Tool | Purpose |\n",
        "|----------|------|---------||\n",
        "| **Experiment Tracking** | MLflow | Parameters, metrics, models |\n",
        "| | Weights & Biases | Similar + collaboration |\n",
        "| **Model Serving** | FastAPI | REST API |\n",
        "| | BentoML | ML-focused serving |\n",
        "| | Seldon/KServe | Kubernetes-native |\n",
        "| **Containerization** | Docker | Environment isolation |\n",
        "| | Kubernetes | Orchestration |\n",
        "| **Data Versioning** | DVC | Git for data |\n",
        "| | Delta Lake | ACID transactions |\n",
        "| **Monitoring** | Evidently | ML monitoring |\n",
        "| | Prometheus/Grafana | Metrics + dashboards |\n",
        "| **CI/CD** | GitHub Actions | Automation |\n",
        "| | GitLab CI | Alternative |\n",
        "| **Feature Store** | Feast | Feature management |\n",
        "\n",
        "---\n",
        "\n",
        "## 🎉 Phase 7 Complete!\n",
        "\n",
        "**Вы теперь знаете:**\n",
        "\n",
        "- ✅ MLflow experiment tracking и Model Registry\n",
        "- ✅ Model serialization (pickle, joblib)\n",
        "- ✅ FastAPI для ML API с Pydantic validation\n",
        "- ✅ Docker containerization (multi-stage builds)\n",
        "- ✅ Data drift detection (KS test, Chi-squared)\n",
        "- ✅ Model performance monitoring\n",
        "- ✅ CI/CD с GitHub Actions\n",
        "- ✅ DVC для data versioning\n",
        "\n",
        "---\n",
        "\n",
        "## 🏆 ML Roadmap Complete!\n",
        "\n",
        "**Весь путь от начала до production:**\n",
        "\n",
        "1. ✅ **Phase 1:** Classification Basics (Titanic)\n",
        "2. ✅ **Phase 2:** Deep Learning (MNIST, PyTorch)\n",
        "3. ✅ **Phase 3:** Advanced Ensembles (Stacking, Blending)\n",
        "4. ✅ **Phase 4:** Transformers (Self-Attention, TFT)\n",
        "5. ✅ **Phase 5:** Anomaly Detection (Isolation Forest, Autoencoders)\n",
        "6. ✅ **Phase 6:** Explainable AI (SHAP, LIME, Fairness)\n",
        "7. ✅ **Phase 7:** Production MLOps (FastAPI, Docker, CI/CD)\n",
        "\n",
        "**Теперь вы готовы:**\n",
        "\n",
        "- 🎯 Решать real-world ML задачи\n",
        "- 🎯 Выбирать правильные модели и методы\n",
        "- 🎯 Деплоить модели в production\n",
        "- 🎯 Мониторить и поддерживать ML системы\n",
        "- 🎯 Объяснять predictions и обеспечивать fairness\n",
        "\n",
        "---\n",
        "\n",
        "**🚀 You're now a Production-Ready ML Practitioner!**\n"
    ]
})

# Сохраняем финальный notebook
notebook['cells'] = cells

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f'\\n✅ Phase 7 notebook complete: {notebook_path}')
print(f'Total cells: {len(cells)}')
print('')
print('📊 Phase 7 Summary:')
print('- Introduction & MLOps Overview (3 cells)')
print('- Dataset & Preprocessing (3 cells)')
print('- MLflow Experiment Tracking (6 cells)')
print('- Model Serialization (2 cells)')
print('- FastAPI Development (4 cells)')
print('- Docker Containerization (3 cells)')
print('- Monitoring & Drift Detection (6 cells)')
print('- CI/CD for ML (2 cells)')
print('- DVC Data Versioning (2 cells)')
print('- Conclusions & Best Practices (1 cell)')
print('')
print('Total: 38 cells - Complete Production MLOps!')
