#!/usr/bin/env python3
"""
Создание финального ноутбука: Integration & Comparison
Сравнение всех методов Phase 1 Classical ML на одном датасете
"""

import json

# Создаем базовую структуру ноутбука
notebook = {
    "cells": [],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.8.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

cells = []

# ============================================================================
# TITLE
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🎯 Integration & Comparison: Phase 1 Classical ML\n",
        "\n",
        "**Цель:** Финальное сравнение всех изученных методов на едином датасете\n",
        "\n",
        "---\n",
        "\n",
        "## 🎯 Цели ноутбука\n",
        "\n",
        "1. **Объединение знаний** из всех ноутбуков Phase 1\n",
        "2. **Честное сравнение** всех методов на одном датасете\n",
        "3. **Практические рекомендации** по выбору алгоритмов\n",
        "4. **Best practices** для production ML систем\n",
        "\n",
        "---\n",
        "\n",
        "## 📚 Что мы изучили в Phase 1:\n",
        "\n",
        "| Ноутбук | Тема | Ключевые концепции |\n",
        "|---------|------|-------------------|\n",
        "| **01** | XGBoost Deep Dive | Gradient boosting, second-order optimization, regularization |\n",
        "| **02** | LightGBM Deep Dive | Histogram-based, GOSS, EFB, leaf-wise growth |\n",
        "| **03** | CatBoost Deep Dive | Ordered boosting, categorical features, symmetric trees |\n",
        "| **04** | Stacking Ensemble | Meta-learning, out-of-fold predictions, diversity |\n",
        "| **05** | Imbalanced Data | SMOTE, cost-sensitive learning, threshold optimization |\n",
        "| **06** | Advanced Feature Engineering | Polynomial, target encoding, feature selection |\n",
        "\n",
        "---\n",
        "\n",
        "## 💼 Бизнес-задача: Telco Customer Churn\n",
        "\n",
        "**Контекст:** Телеком компания теряет 27% клиентов ежегодно.\n",
        "\n",
        "**Проблемы:**\n",
        "- 📊 **Imbalanced data:** ~27% churn (не extreme, но moderate)\n",
        "- 🔢 **Категориальные признаки:** Услуги, тип контракта (high cardinality)\n",
        "- 💰 **Разная стоимость ошибок:** FN (упущенный churn) дороже FP\n",
        "- 🎯 **Бизнес-цель:** Предотвратить churn с retention campaigns\n",
        "\n",
        "**Метрики:**\n",
        "- **ROC-AUC:** Общая способность различать классы\n",
        "- **Precision/Recall/F1:** Баланс FP/FN\n",
        "- **Business Cost:** Weighted cost (FN = $500, FP = $50)\n",
        "\n",
        "**Почему этот датасет?**\n",
        "- ✅ Позволяет применить **все** техники Phase 1\n",
        "- ✅ Категориальные признаки → тестируем CatBoost, Target Encoding\n",
        "- ✅ Moderate imbalance → SMOTE, class weights\n",
        "- ✅ Малый размер (~7k) → можно быстро экспериментировать\n",
        "\n",
        "---"
    ]
})

# ============================================================================
# THEORY: COMPARISON OF METHODS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📚 Часть 1: Теоретическое сравнение методов\n",
        "\n",
        "### 1.1 Gradient Boosting семейство\n",
        "\n",
        "#### Общая идея Gradient Boosting\n",
        "\n",
        "**Формула (Friedman, 2001):**\n",
        "\n",
        "$$F_m(x) = F_{m-1}(x) + \\nu \\cdot h_m(x)$$\n",
        "\n",
        "где:\n",
        "- $F_m(x)$ — ансамбль из $m$ деревьев\n",
        "- $h_m(x)$ — новое дерево, обучаемое на градиентах\n",
        "- $\\nu$ — learning rate (shrinkage)\n",
        "\n",
        "**Градиент:**\n",
        "\n",
        "$$g_i = \\frac{\\partial L(y_i, F_{m-1}(x_i))}{\\partial F_{m-1}(x_i)}$$\n",
        "\n",
        "Каждое дерево приближает **anti-gradient** loss функции.\n",
        "\n",
        "---"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.2 XGBoost vs LightGBM vs CatBoost\n",
        "\n",
        "#### Детальное сравнение\n",
        "\n",
        "**1. XGBoost (Chen & Guestrin, 2016)**\n",
        "\n",
        "**Ключевая идея:** Second-order optimization\n",
        "\n",
        "$$L = \\sum_{i=1}^n \\left[ g_i f_t(x_i) + \\frac{1}{2} h_i f_t^2(x_i) \\right] + \\Omega(f_t)$$\n",
        "\n",
        "где:\n",
        "- $g_i$ — first-order gradient\n",
        "- $h_i$ — second-order gradient (Hessian)\n",
        "- $\\Omega(f_t) = \\gamma T + \\frac{1}{2}\\lambda \\sum_{j=1}^T w_j^2$ — regularization\n",
        "\n",
        "**Преимущества:**\n",
        "- ✅ Точная оптимизация (Newton's method)\n",
        "- ✅ Сильная регуляризация (L1/L2, gamma, alpha)\n",
        "- ✅ Стабильность и зрелость\n",
        "- ✅ Отличная документация и community\n",
        "\n",
        "**Недостатки:**\n",
        "- ❌ Медленнее LightGBM на больших данных\n",
        "- ❌ Больше памяти (pre-sorted или histogram)\n",
        "- ❌ Категориальные нужно кодировать вручную\n",
        "\n",
        "---\n",
        "\n",
        "**2. LightGBM (Ke et al., 2017)**\n",
        "\n",
        "**Ключевые идеи:**\n",
        "\n",
        "**a) Histogram-based splits**\n",
        "\n",
        "Вместо сортировки всех значений → bins (обычно 255):\n",
        "\n",
        "$$\\text{bin}(x) = \\left\\lfloor \\frac{x - \\min(x)}{\\text{bin\\_width}} \\right\\rfloor$$\n",
        "\n",
        "**b) GOSS (Gradient-based One-Side Sampling)**\n",
        "\n",
        "```\n",
        "1. Сортировать примеры по |gradient|\n",
        "2. Взять top-a% (большие градиенты)\n",
        "3. Случайно взять b% из оставшихся\n",
        "4. Взвесить малые градиенты на (1-a)/b\n",
        "```\n",
        "\n",
        "**c) Leaf-wise (best-first) growth**\n",
        "\n",
        "Вместо level-wise → выбираем leaf с максимальным gain:\n",
        "\n",
        "$$\\text{Gain} = \\frac{1}{2} \\left[ \\frac{G_L^2}{H_L + \\lambda} + \\frac{G_R^2}{H_R + \\lambda} - \\frac{(G_L + G_R)^2}{H_L + H_R + \\lambda} \\right] - \\gamma$$\n",
        "\n",
        "**Преимущества:**\n",
        "- ✅ **5-20x быстрее** XGBoost на больших данных\n",
        "- ✅ Меньше памяти (~50%)\n",
        "- ✅ Native categorical support\n",
        "- ✅ Лучше на sparse данных (EFB)\n",
        "\n",
        "**Недостатки:**\n",
        "- ❌ Склонен к overfitting (leaf-wise aggressive)\n",
        "- ❌ Требует тщательного tuning\n",
        "- ❌ Хуже на малых данных (<10k)\n",
        "\n",
        "---\n",
        "\n",
        "**3. CatBoost (Prokhorenkova et al., 2018)**\n",
        "\n",
        "**Ключевые идеи:**\n",
        "\n",
        "**a) Ordered Boosting**\n",
        "\n",
        "Решение проблемы **prediction shift** — используем разные модели:\n",
        "\n",
        "$$F_{<i}(x_i) = \\sum_{t=1}^{T} h_t^{<i}(x_i)$$\n",
        "\n",
        "Модель $F_{<i}$ обучена **без** примера $i$.\n",
        "\n",
        "**b) Ordered Target Statistics (для categorical)**\n",
        "\n",
        "$$\\hat{x}_k^i = \\frac{\\sum_{j=1}^{p-1} [x_j = x_k] \\cdot y_{\\sigma_j} + a \\cdot p}{\\sum_{j=1}^{p-1} [x_j = x_k] + a}$$\n",
        "\n",
        "где $\\sigma$ — случайная перестановка, $p$ — позиция примера $i$, $a$ — prior weight.\n",
        "\n",
        "**c) Symmetric (Oblivious) Trees**\n",
        "\n",
        "Все листья на одном уровне используют одинаковый split → быстрый inference.\n",
        "\n",
        "**Преимущества:**\n",
        "- ✅ **Лучшие categorical features** из коробки\n",
        "- ✅ Меньше overfitting (ordered boosting)\n",
        "- ✅ Отличное качество **по умолчанию** (меньше tuning)\n",
        "- ✅ GPU support\n",
        "\n",
        "**Недостатки:**\n",
        "- ❌ Медленнее обучение (ordered boosting сложнее)\n",
        "- ❌ Больше памяти при обучении\n",
        "- ❌ Symmetric trees могут быть менее гибкими\n",
        "\n",
        "---"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.3 Когда использовать какой алгоритм?\n",
        "\n",
        "#### Практическая таблица выбора\n",
        "\n",
        "| Сценарий | Рекомендация | Почему |\n",
        "|----------|-------------|--------|\n",
        "| **Малые данные (<10k)** | XGBoost | Стабильнее, level-wise безопаснее |\n",
        "| **Средние данные (10k-1M)** | XGBoost или CatBoost | Зависит от categorical features |\n",
        "| **Большие данные (>1M)** | LightGBM | В 5-20x быстрее |\n",
        "| **Много categorical** | CatBoost | Native support, ordered target stats |\n",
        "| **Разреженные данные** | LightGBM | EFB оптимизация |\n",
        "| **Первая модель (baseline)** | XGBoost | Меньше tuning, хорошие defaults |\n",
        "| **Production-critical** | XGBoost | Зрелость, стабильность |\n",
        "| **Скорость inference** | CatBoost | Symmetric trees быстрее |\n",
        "| **Ограниченная память** | LightGBM | Histogram-based |\n",
        "| **Kaggle competition** | Ensemble всех трех! | Diversity → лучше ensemble |\n",
        "\n",
        "#### Эмпирические результаты\n",
        "\n",
        "**Из Kaggle competitions и research:**\n",
        "\n",
        "1. **Качество (ROC-AUC):**\n",
        "   - Большие данные: LightGBM ≥ CatBoost > XGBoost (разница ~0.5-2%)\n",
        "   - Малые данные: XGBoost ≥ CatBoost ≥ LightGBM\n",
        "   - С категориальными: CatBoost часто лучший\n",
        "\n",
        "2. **Скорость обучения:**\n",
        "   - LightGBM: **5-20x** быстрее XGBoost на >100k примеров\n",
        "   - CatBoost: **2-3x** медленнее XGBoost (ordered boosting)\n",
        "   - XGBoost: baseline скорость\n",
        "\n",
        "3. **Память:**\n",
        "   - LightGBM: **~50%** от XGBoost\n",
        "   - CatBoost: **~150%** от XGBoost при обучении\n",
        "   - XGBoost: baseline\n",
        "\n",
        "4. **Tuning сложность:**\n",
        "   - XGBoost: Средняя (хорошие defaults)\n",
        "   - LightGBM: Высокая (leaf-wise нужен контроль)\n",
        "   - CatBoost: **Низкая** (отличные defaults!)\n",
        "\n",
        "---"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.4 Stacking: Когда и как?\n",
        "\n",
        "#### Теория Stacking\n",
        "\n",
        "**Wolpert's Stacked Generalization (1992):**\n",
        "\n",
        "**Level 0 (Base learners):**\n",
        "\n",
        "$$\\hat{y}_i^{(k)} = f_k(x_i), \\quad k = 1, \\ldots, K$$\n",
        "\n",
        "**Level 1 (Meta-learner):**\n",
        "\n",
        "$$\\hat{y}_i = g\\left( \\hat{y}_i^{(1)}, \\hat{y}_i^{(2)}, \\ldots, \\hat{y}_i^{(K)} \\right)$$\n",
        "\n",
        "**Out-of-fold predictions (избегаем overfitting):**\n",
        "\n",
        "```\n",
        "For fold k in K-Fold:\n",
        "  1. Train base learners на train_k\n",
        "  2. Predict на val_k → oof_predictions_k\n",
        "  3. Predict на test → test_predictions_k\n",
        "  \n",
        "Meta features = concat(oof_predictions_1, ..., oof_predictions_K)\n",
        "Meta learner.fit(Meta features, y)\n",
        "```\n",
        "\n",
        "#### Когда Stacking работает?\n",
        "\n",
        "**Ключевое условие:** Diversity базовых моделей!\n",
        "\n",
        "**Ambiguity Decomposition (Krogh & Vedelsby, 1995):**\n",
        "\n",
        "$$E_{\\text{ensemble}} = \\bar{E} - \\bar{A}$$\n",
        "\n",
        "где:\n",
        "- $\\bar{E}$ — средняя ошибка базовых моделей\n",
        "- $\\bar{A}$ — средняя ambiguity (diversity)\n",
        "\n",
        "**Чем больше diversity, тем меньше ошибка ensemble!**\n",
        "\n",
        "#### Как создать diversity?\n",
        "\n",
        "1. **Разные алгоритмы:** XGBoost + LightGBM + CatBoost + Logistic Regression\n",
        "2. **Разные признаки:** Один с polynomial, другой с target encoding\n",
        "3. **Разные гиперпараметры:** Shallow vs deep trees\n",
        "4. **Разные подвыборки:** Bagging на разных частях данных\n",
        "\n",
        "#### Практические рекомендации:\n",
        "\n",
        "✅ **Используйте Stacking если:**\n",
        "- Есть время на обучение нескольких моделей\n",
        "- Нужны последние проценты качества (Kaggle, research)\n",
        "- Базовые модели достаточно разные\n",
        "\n",
        "❌ **НЕ используйте Stacking если:**\n",
        "- Нужна скорость inference (в 3-5x медленнее)\n",
        "- Ограниченные ресурсы (обучение всех моделей долго)\n",
        "- Базовые модели очень похожи (мало diversity)\n",
        "- Production система с простотой поддержки\n",
        "\n",
        "**Типичный прирост:** 0.5-3% ROC-AUC поверх лучшей базовой модели.\n",
        "\n",
        "---"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.5 Feature Engineering: Возврат инвестиций\n",
        "\n",
        "#### Влияние на качество модели\n",
        "\n",
        "**Эмпирическое правило (Andrew Ng):**\n",
        "\n",
        "| Компонент | Влияние на качество | Время инвестиций |\n",
        "|-----------|---------------------|------------------|\n",
        "| **Feature Engineering** | 60-70% | Высокое |\n",
        "| Algorithm selection | 15-20% | Среднее |\n",
        "| Hyperparameter tuning | 10-15% | Среднее |\n",
        "| Ensemble | 5-10% | Низкое |\n",
        "\n",
        "#### Эффективность техник\n",
        "\n",
        "**Из нашего опыта (Notebook 06):**\n",
        "\n",
        "| Техника | Прирост качества | Когда использовать |\n",
        "|---------|-----------------|-------------------|\n",
        "| **Log transform** | 5-10% | Skewed данные (цены, площади) |\n",
        "| **Target encoding** | 3-7% | High cardinality categorical |\n",
        "| **Polynomial features** | 5-15% | Линейные модели, малые данные |\n",
        "| **Feature selection** | 2-5% | Много шума, overfitting |\n",
        "| **Domain features** | 10-30%! | Когда есть domain knowledge |\n",
        "\n",
        "#### Важность для разных алгоритмов\n",
        "\n",
        "**Linear models (Logistic Regression, SVM):**\n",
        "- ⭐⭐⭐⭐⭐ Критично! (нужны interactions, scaling, transformations)\n",
        "\n",
        "**Tree-based models (XGBoost, RF):**\n",
        "- ⭐⭐⭐ Полезно (domain features, target encoding)\n",
        "- Polynomial interactions НЕ нужны (деревья сами их находят)\n",
        "\n",
        "**Neural Networks:**\n",
        "- ⭐⭐ Может помочь, но сети часто учат сами (feature learning)\n",
        "\n",
        "---"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1.6 Imbalanced Data: Стратегия выбора техники\n",
        "\n",
        "#### Классификация по степени imbalance\n",
        "\n",
        "| Imbalance ratio | Категория | Рекомендация |\n",
        "|----------------|-----------|-------------|\n",
        "| 1:1 - 1:4 | Balanced/Mild | Ничего не нужно |\n",
        "| 1:4 - 1:20 | Moderate | Class weights |\n",
        "| 1:20 - 1:100 | High | SMOTE + class weights |\n",
        "| 1:100+ | Extreme | Advanced (Focal loss, sampling) |\n",
        "\n",
        "#### Техники и их применимость\n",
        "\n",
        "**1. Class Weights (scale_pos_weight в XGBoost)**\n",
        "\n",
        "$$w_{\\text{pos}} = \\frac{N_{\\text{neg}}}{N_{\\text{pos}}}$$\n",
        "\n",
        "- ✅ Простота\n",
        "- ✅ Работает для tree-based models\n",
        "- ✅ Нет изменения размера данных\n",
        "- ❌ Не создает новые примеры\n",
        "\n",
        "**2. SMOTE (Synthetic Minority Over-sampling)**\n",
        "\n",
        "$$x_{\\text{new}} = x_i + \\lambda \\cdot (x_{\\text{nn}} - x_i), \\quad \\lambda \\in [0, 1]$$\n",
        "\n",
        "- ✅ Создает новые примеры minority класса\n",
        "- ✅ Помогает с diversity\n",
        "- ❌ Может создать noise\n",
        "- ❌ Увеличивает размер данных\n",
        "\n",
        "**3. Hybrid: SMOTE + Class Weights**\n",
        "\n",
        "- ✅ Лучшее из обоих миров\n",
        "- Moderate SMOTE (до 1:10) + weights\n",
        "\n",
        "**4. Focal Loss (Lin et al., 2017)**\n",
        "\n",
        "$$FL(p_t) = -\\alpha_t (1 - p_t)^\\gamma \\log(p_t)$$\n",
        "\n",
        "- ✅ Фокусируется на hard examples\n",
        "- ✅ Автоматически down-weights easy examples\n",
        "- ❌ Нужна custom реализация\n",
        "\n",
        "#### Метрики для imbalanced data\n",
        "\n",
        "**НЕ используйте Accuracy!**\n",
        "\n",
        "**Используйте:**\n",
        "1. **Precision/Recall/F1**\n",
        "2. **PR-AUC** (лучше ROC-AUC для imbalanced)\n",
        "3. **Business cost** (weighted FP и FN)\n",
        "\n",
        "---\n",
        "\n",
        "## Теоретическая часть завершена! Переходим к практике 🚀\n",
        "\n",
        "---"
    ]
})

# ============================================================================
# PRACTICAL: IMPORTS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📊 Часть 2: Практическое сравнение\n",
        "\n",
        "### 2.1 Импорт библиотек"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Основные библиотеки\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from scipy import stats\n",
        "import warnings\n",
        "import time\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "# Gradient Boosting\n",
        "import xgboost as xgb\n",
        "from xgboost import XGBClassifier\n",
        "import lightgbm as lgb\n",
        "from lightgbm import LGBMClassifier\n",
        "import catboost as cb\n",
        "from catboost import CatBoostClassifier\n",
        "\n",
        "# Baseline models\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "\n",
        "# Preprocessing\n",
        "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
        "from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, cross_val_predict\n",
        "\n",
        "# Feature engineering\n",
        "from sklearn.preprocessing import PolynomialFeatures, PowerTransformer\n",
        "from sklearn.feature_selection import SelectKBest, f_classif\n",
        "\n",
        "# Imbalanced data\n",
        "try:\n",
        "    from imblearn.over_sampling import SMOTE\n",
        "    HAS_IMBLEARN = True\n",
        "except ImportError:\n",
        "    print('⚠️ imbalanced-learn не установлен')\n",
        "    HAS_IMBLEARN = False\n",
        "\n",
        "# Metrics\n",
        "from sklearn.metrics import (\n",
        "    accuracy_score, precision_score, recall_score, f1_score,\n",
        "    roc_auc_score, average_precision_score,\n",
        "    confusion_matrix, classification_report,\n",
        "    roc_curve, precision_recall_curve\n",
        ")\n",
        "\n",
        "# Настройка визуализации\n",
        "plt.style.use('seaborn-v0_8-darkgrid')\n",
        "sns.set_palette('husl')\n",
        "%matplotlib inline\n",
        "\n",
        "# Seed\n",
        "RANDOM_STATE = 42\n",
        "np.random.seed(RANDOM_STATE)\n",
        "\n",
        "print('✅ Библиотеки загружены')\n",
        "print(f'XGBoost: {xgb.__version__}')\n",
        "print(f'LightGBM: {lgb.__version__}')\n",
        "print(f'CatBoost: {cb.__version__}')"
    ]
})

# Добавляем все cells
notebook['cells'] = cells

# Сохраняем
output_path = '/home/user/test/notebooks/phase1_classical_ml/07_integration_comparison.ipynb'
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f'✅ Создан ноутбук с {len(cells)} теоретическими ячейками')
print(f'Сохранен: {output_path}')
print('📝 Теория написана прямо в ноутбуке с формулами!')
