#!/usr/bin/env python3
"""
Phase 4 Step 1: Self-Attention & Transformer Basics
Part 4: Training, Evaluation, Attention Visualization, Comparisons
"""

import json

# Загружаем существующий notebook
notebook_path = '/home/user/test/notebooks/phase4_transformers/01_self_attention_transformer.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

cells = notebook['cells']

# ============================================================================
# MODEL TRAINING
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 🏋️ Часть 6: Обучение Transformer\n",
        "\n",
        "### 6.1 Инициализация модели"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Hyperparameters\n",
        "num_features = X_train.shape[1]\n",
        "d_model = 64\n",
        "n_heads = 4\n",
        "n_layers = 2\n",
        "d_ff = 256  # 4 * d_model\n",
        "num_classes = 2\n",
        "dropout = 0.1\n",
        "pooling = 'mean'  # 'mean', 'max', or 'cls'\n",
        "\n",
        "print(\"Model Hyperparameters:\")\n",
        "print(f\"  Input features: {num_features}\")\n",
        "print(f\"  d_model: {d_model}\")\n",
        "print(f\"  n_heads: {n_heads}\")\n",
        "print(f\"  n_layers: {n_layers}\")\n",
        "print(f\"  d_ff: {d_ff}\")\n",
        "print(f\"  dropout: {dropout}\")\n",
        "print(f\"  pooling: {pooling}\")\n",
        "print(f\"  num_classes: {num_classes}\")\n",
        "\n",
        "# Initialize model\n",
        "model = TabularTransformerEncoder(\n",
        "    num_features=num_features,\n",
        "    d_model=d_model,\n",
        "    n_heads=n_heads,\n",
        "    n_layers=n_layers,\n",
        "    d_ff=d_ff,\n",
        "    num_classes=num_classes,\n",
        "    dropout=dropout,\n",
        "    pooling=pooling\n",
        ").to(device)\n",
        "\n",
        "# Count parameters\n",
        "total_params = sum(p.numel() for p in model.parameters())\n",
        "trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
        "\n",
        "print(f\"\\nModel size:\")\n",
        "print(f\"  Total parameters: {total_params:,}\")\n",
        "print(f\"  Trainable parameters: {trainable_params:,}\")\n",
        "\n",
        "# Loss and optimizer\n",
        "criterion = nn.CrossEntropyLoss()\n",
        "optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)\n",
        "scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', \n",
        "                                                   factor=0.5, patience=5)\n",
        "\n",
        "print(\"\\n✅ Model initialized!\")"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 6.2 Training Loop"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Training function\n",
        "def train_epoch(model, loader, criterion, optimizer, device):\n",
        "    model.train()\n",
        "    total_loss = 0\n",
        "    correct = 0\n",
        "    total = 0\n",
        "    \n",
        "    for X_batch, y_batch in loader:\n",
        "        X_batch = X_batch.to(device)\n",
        "        y_batch = y_batch.to(device)\n",
        "        \n",
        "        # Forward pass\n",
        "        optimizer.zero_grad()\n",
        "        outputs = model(X_batch)\n",
        "        loss = criterion(outputs, y_batch)\n",
        "        \n",
        "        # Backward pass\n",
        "        loss.backward()\n",
        "        optimizer.step()\n",
        "        \n",
        "        # Metrics\n",
        "        total_loss += loss.item() * X_batch.size(0)\n",
        "        _, predicted = torch.max(outputs, 1)\n",
        "        correct += (predicted == y_batch).sum().item()\n",
        "        total += y_batch.size(0)\n",
        "    \n",
        "    avg_loss = total_loss / total\n",
        "    accuracy = correct / total\n",
        "    return avg_loss, accuracy\n",
        "\n",
        "\n",
        "# Evaluation function\n",
        "def evaluate(model, loader, criterion, device):\n",
        "    model.eval()\n",
        "    total_loss = 0\n",
        "    correct = 0\n",
        "    total = 0\n",
        "    \n",
        "    with torch.no_grad():\n",
        "        for X_batch, y_batch in loader:\n",
        "            X_batch = X_batch.to(device)\n",
        "            y_batch = y_batch.to(device)\n",
        "            \n",
        "            outputs = model(X_batch)\n",
        "            loss = criterion(outputs, y_batch)\n",
        "            \n",
        "            total_loss += loss.item() * X_batch.size(0)\n",
        "            _, predicted = torch.max(outputs, 1)\n",
        "            correct += (predicted == y_batch).sum().item()\n",
        "            total += y_batch.size(0)\n",
        "    \n",
        "    avg_loss = total_loss / total\n",
        "    accuracy = correct / total\n",
        "    return avg_loss, accuracy\n",
        "\n",
        "print(\"✅ Training functions defined\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Training loop\n",
        "num_epochs = 50\n",
        "history = {\n",
        "    'train_loss': [],\n",
        "    'train_acc': [],\n",
        "    'test_loss': [],\n",
        "    'test_acc': []\n",
        "}\n",
        "\n",
        "print(f\"Training for {num_epochs} epochs...\\n\")\n",
        "best_test_acc = 0\n",
        "\n",
        "for epoch in range(num_epochs):\n",
        "    # Train\n",
        "    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)\n",
        "    \n",
        "    # Evaluate\n",
        "    test_loss, test_acc = evaluate(model, test_loader, criterion, device)\n",
        "    \n",
        "    # Scheduler step\n",
        "    scheduler.step(test_loss)\n",
        "    \n",
        "    # Save history\n",
        "    history['train_loss'].append(train_loss)\n",
        "    history['train_acc'].append(train_acc)\n",
        "    history['test_loss'].append(test_loss)\n",
        "    history['test_acc'].append(test_acc)\n",
        "    \n",
        "    # Track best\n",
        "    if test_acc > best_test_acc:\n",
        "        best_test_acc = test_acc\n",
        "    \n",
        "    # Print progress\n",
        "    if (epoch + 1) % 10 == 0 or epoch == 0:\n",
        "        print(f\"Epoch [{epoch+1}/{num_epochs}]\")\n",
        "        print(f\"  Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}\")\n",
        "        print(f\"  Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.4f}\")\n",
        "        print(f\"  LR: {optimizer.param_groups[0]['lr']:.6f}\")\n",
        "        print()\n",
        "\n",
        "print(f\"\\n✅ Training completed!\")\n",
        "print(f\"Best Test Accuracy: {best_test_acc:.4f}\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Plot training history\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Loss\n",
        "axes[0].plot(history['train_loss'], label='Train Loss', linewidth=2)\n",
        "axes[0].plot(history['test_loss'], label='Test Loss', linewidth=2)\n",
        "axes[0].set_title('Loss over Epochs', fontsize=16, fontweight='bold')\n",
        "axes[0].set_xlabel('Epoch', fontsize=12)\n",
        "axes[0].set_ylabel('Loss', fontsize=12)\n",
        "axes[0].legend()\n",
        "axes[0].grid(alpha=0.3)\n",
        "\n",
        "# Accuracy\n",
        "axes[1].plot(history['train_acc'], label='Train Accuracy', linewidth=2)\n",
        "axes[1].plot(history['test_acc'], label='Test Accuracy', linewidth=2)\n",
        "axes[1].set_title('Accuracy over Epochs', fontsize=16, fontweight='bold')\n",
        "axes[1].set_xlabel('Epoch', fontsize=12)\n",
        "axes[1].set_ylabel('Accuracy', fontsize=12)\n",
        "axes[1].legend()\n",
        "axes[1].grid(alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"Final Train Accuracy: {history['train_acc'][-1]:.4f}\")\n",
        "print(f\"Final Test Accuracy: {history['test_acc'][-1]:.4f}\")\n",
        "print(f\"Best Test Accuracy: {best_test_acc:.4f}\")"
    ]
})

# ============================================================================
# DETAILED EVALUATION
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 6.3 Detailed Evaluation"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Get predictions\n",
        "model.eval()\n",
        "y_pred = []\n",
        "y_true = []\n",
        "y_probs = []\n",
        "\n",
        "with torch.no_grad():\n",
        "    for X_batch, y_batch in test_loader:\n",
        "        X_batch = X_batch.to(device)\n",
        "        outputs = model(X_batch)\n",
        "        probs = F.softmax(outputs, dim=1)\n",
        "        _, predicted = torch.max(outputs, 1)\n",
        "        \n",
        "        y_pred.extend(predicted.cpu().numpy())\n",
        "        y_true.extend(y_batch.numpy())\n",
        "        y_probs.extend(probs[:, 1].cpu().numpy())  # probability of class 1\n",
        "\n",
        "y_pred = np.array(y_pred)\n",
        "y_true = np.array(y_true)\n",
        "y_probs = np.array(y_probs)\n",
        "\n",
        "# Metrics\n",
        "accuracy = accuracy_score(y_true, y_pred)\n",
        "precision = precision_score(y_true, y_pred)\n",
        "recall = recall_score(y_true, y_pred)\n",
        "f1 = f1_score(y_true, y_pred)\n",
        "auc = roc_auc_score(y_true, y_probs)\n",
        "\n",
        "print(\"Test Set Performance:\")\n",
        "print(f\"  Accuracy:  {accuracy:.4f}\")\n",
        "print(f\"  Precision: {precision:.4f}\")\n",
        "print(f\"  Recall:    {recall:.4f}\")\n",
        "print(f\"  F1 Score:  {f1:.4f}\")\n",
        "print(f\"  ROC AUC:   {auc:.4f}\")\n",
        "\n",
        "# Classification report\n",
        "print(\"\\nClassification Report:\")\n",
        "print(classification_report(y_true, y_pred, target_names=['Died', 'Survived']))\n",
        "\n",
        "# Confusion Matrix\n",
        "cm = confusion_matrix(y_true, y_pred)\n",
        "plt.figure(figsize=(8, 6))\n",
        "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', \n",
        "            xticklabels=['Died', 'Survived'],\n",
        "            yticklabels=['Died', 'Survived'],\n",
        "            cbar_kws={'label': 'Count'})\n",
        "plt.title('Confusion Matrix', fontsize=16, fontweight='bold')\n",
        "plt.xlabel('Predicted', fontsize=12)\n",
        "plt.ylabel('True', fontsize=12)\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# ============================================================================
# ATTENTION VISUALIZATION
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 🔍 Часть 7: Attention Visualization\n",
        "\n",
        "### 7.1 Визуализация Attention Weights\n",
        "\n",
        "**Что мы ищем:**\n",
        "- Какие features модель считает важными?\n",
        "- Есть ли паттерны в attention между features?\n",
        "- Как разные heads специализируются?"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Выбираем несколько примеров для визуализации\n",
        "sample_indices = [0, 5, 10]  # индексы в test set\n",
        "\n",
        "# Feature names\n",
        "feature_names = [col for col in data.columns if col != 'survived']\n",
        "print(f\"Features ({len(feature_names)}): {feature_names}\")\n",
        "\n",
        "# Get attention weights для выбранных примеров\n",
        "model.eval()\n",
        "with torch.no_grad():\n",
        "    for idx in sample_indices:\n",
        "        x_sample = X_test_tensor[idx:idx+1].to(device)\n",
        "        y_sample = y_test_tensor[idx].item()\n",
        "        \n",
        "        # Forward pass with attention\n",
        "        logits, attention_list = model(x_sample, return_attention=True)\n",
        "        pred_prob = F.softmax(logits, dim=1)[0, 1].item()\n",
        "        pred_class = torch.argmax(logits, dim=1).item()\n",
        "        \n",
        "        print(f\"\\n{'='*60}\")\n",
        "        print(f\"Sample {idx}: True={y_sample}, Pred={pred_class}, Prob={pred_prob:.3f}\")\n",
        "        print(f\"{'='*60}\")\n",
        "        \n",
        "        # Визуализируем attention weights для всех layers\n",
        "        n_layers_viz = len(attention_list)\n",
        "        n_heads_viz = attention_list[0].size(1)\n",
        "        \n",
        "        fig, axes = plt.subplots(n_layers_viz, n_heads_viz, \n",
        "                                figsize=(n_heads_viz * 4, n_layers_viz * 4))\n",
        "        \n",
        "        if n_layers_viz == 1:\n",
        "            axes = axes.reshape(1, -1)\n",
        "        \n",
        "        for layer_idx in range(n_layers_viz):\n",
        "            attn_weights = attention_list[layer_idx][0].cpu().numpy()  # (n_heads, seq_len, seq_len)\n",
        "            \n",
        "            for head_idx in range(n_heads_viz):\n",
        "                ax = axes[layer_idx, head_idx]\n",
        "                \n",
        "                # Attention matrix для этого head\n",
        "                attn_matrix = attn_weights[head_idx]  # (seq_len, seq_len)\n",
        "                \n",
        "                sns.heatmap(attn_matrix, annot=False, fmt='.2f', cmap='YlOrRd',\n",
        "                           xticklabels=feature_names, yticklabels=feature_names,\n",
        "                           ax=ax, cbar=True, square=True)\n",
        "                ax.set_title(f'Layer {layer_idx+1}, Head {head_idx+1}', \n",
        "                           fontsize=12, fontweight='bold')\n",
        "                ax.set_xlabel('Keys (attending to)')\n",
        "                if head_idx == 0:\n",
        "                    ax.set_ylabel('Queries (attending from)')\n",
        "        \n",
        "        plt.suptitle(f'Sample {idx}: Attention Weights Across Layers and Heads\\n'\n",
        "                    f'True: {y_sample}, Pred: {pred_class}, Prob: {pred_prob:.3f}',\n",
        "                    fontsize=16, fontweight='bold', y=1.01)\n",
        "        plt.tight_layout()\n",
        "        plt.show()"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Aggregate attention weights across all test samples\n",
        "# Для понимания, какие features модель считает важными в среднем\n",
        "\n",
        "model.eval()\n",
        "all_attention_weights = []\n",
        "\n",
        "with torch.no_grad():\n",
        "    for X_batch, _ in test_loader:\n",
        "        X_batch = X_batch.to(device)\n",
        "        _, attention_list = model(X_batch, return_attention=True)\n",
        "        \n",
        "        # Берем только последний layer\n",
        "        last_layer_attn = attention_list[-1]  # (batch, n_heads, seq_len, seq_len)\n",
        "        \n",
        "        # Усредняем по heads\n",
        "        avg_attn = last_layer_attn.mean(dim=1)  # (batch, seq_len, seq_len)\n",
        "        \n",
        "        all_attention_weights.append(avg_attn.cpu())\n",
        "\n",
        "# Concatenate и усредняем по всем samples\n",
        "all_attention_weights = torch.cat(all_attention_weights, dim=0)\n",
        "mean_attention = all_attention_weights.mean(dim=0).numpy()  # (seq_len, seq_len)\n",
        "\n",
        "print(f\"Mean attention shape: {mean_attention.shape}\")\n",
        "\n",
        "# Визуализируем среднюю attention matrix\n",
        "plt.figure(figsize=(10, 8))\n",
        "sns.heatmap(mean_attention, annot=True, fmt='.2f', cmap='YlOrRd',\n",
        "           xticklabels=feature_names, yticklabels=feature_names,\n",
        "           cbar_kws={'label': 'Attention Weight'})\n",
        "plt.title('Mean Attention Weights (Last Layer, Averaged over Test Set)', \n",
        "         fontsize=16, fontweight='bold')\n",
        "plt.xlabel('Keys (attending to)', fontsize=12)\n",
        "plt.ylabel('Queries (attending from)', fontsize=12)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Вычисляем важность features (сколько на них обращают внимание)\n",
        "feature_importance = mean_attention.sum(axis=0)  # сумма по columns (куда смотрят)\n",
        "\n",
        "# Нормализуем\n",
        "feature_importance = feature_importance / feature_importance.sum()\n",
        "\n",
        "# Сортируем\n",
        "importance_df = pd.DataFrame({\n",
        "    'Feature': feature_names,\n",
        "    'Importance': feature_importance\n",
        "}).sort_values('Importance', ascending=False)\n",
        "\n",
        "print(\"\\nFeature Importance (based on attention):\")\n",
        "print(importance_df)\n",
        "\n",
        "# Визуализируем\n",
        "plt.figure(figsize=(10, 6))\n",
        "plt.barh(importance_df['Feature'], importance_df['Importance'], color='steelblue')\n",
        "plt.xlabel('Attention-based Importance', fontsize=12)\n",
        "plt.title('Feature Importance from Attention Weights', fontsize=16, fontweight='bold')\n",
        "plt.gca().invert_yaxis()\n",
        "plt.grid(alpha=0.3, axis='x')\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# ============================================================================
# COMPARISON WITH BASELINES
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 📊 Часть 8: Сравнение с Baseline моделями\n",
        "\n",
        "### 8.1 Simple MLP Baseline"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Simple MLP для сравнения\n",
        "class SimpleMLP(nn.Module):\n",
        "    def __init__(self, input_size, hidden_sizes, num_classes, dropout=0.3):\n",
        "        super(SimpleMLP, self).__init__()\n",
        "        layers = []\n",
        "        \n",
        "        prev_size = input_size\n",
        "        for hidden_size in hidden_sizes:\n",
        "            layers.append(nn.Linear(prev_size, hidden_size))\n",
        "            layers.append(nn.ReLU())\n",
        "            layers.append(nn.Dropout(dropout))\n",
        "            prev_size = hidden_size\n",
        "        \n",
        "        layers.append(nn.Linear(prev_size, num_classes))\n",
        "        self.network = nn.Sequential(*layers)\n",
        "    \n",
        "    def forward(self, x):\n",
        "        return self.network(x)\n",
        "\n",
        "# Train MLP\n",
        "mlp = SimpleMLP(input_size=num_features, hidden_sizes=[64, 32], \n",
        "                num_classes=2, dropout=0.3).to(device)\n",
        "\n",
        "mlp_optimizer = optim.Adam(mlp.parameters(), lr=0.001, weight_decay=1e-5)\n",
        "mlp_criterion = nn.CrossEntropyLoss()\n",
        "\n",
        "print(f\"Training MLP for {num_epochs} epochs...\")\n",
        "mlp_best_acc = 0\n",
        "\n",
        "for epoch in range(num_epochs):\n",
        "    mlp.train()\n",
        "    for X_batch, y_batch in train_loader:\n",
        "        X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
        "        mlp_optimizer.zero_grad()\n",
        "        outputs = mlp(X_batch)\n",
        "        loss = mlp_criterion(outputs, y_batch)\n",
        "        loss.backward()\n",
        "        mlp_optimizer.step()\n",
        "    \n",
        "    # Evaluate\n",
        "    if (epoch + 1) % 10 == 0 or epoch == 0:\n",
        "        _, test_acc = evaluate(mlp, test_loader, mlp_criterion, device)\n",
        "        if test_acc > mlp_best_acc:\n",
        "            mlp_best_acc = test_acc\n",
        "        print(f\"Epoch [{epoch+1}/{num_epochs}] MLP Test Acc: {test_acc:.4f}\")\n",
        "\n",
        "print(f\"\\nMLP Best Test Accuracy: {mlp_best_acc:.4f}\")"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 8.2 XGBoost Baseline"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# XGBoost baseline\n",
        "try:\n",
        "    import xgboost as xgb\n",
        "    \n",
        "    print(\"Training XGBoost...\")\n",
        "    xgb_model = xgb.XGBClassifier(\n",
        "        n_estimators=100,\n",
        "        max_depth=5,\n",
        "        learning_rate=0.1,\n",
        "        random_state=42\n",
        "    )\n",
        "    \n",
        "    xgb_model.fit(X_train, y_train)\n",
        "    xgb_pred = xgb_model.predict(X_test)\n",
        "    xgb_acc = accuracy_score(y_test, xgb_pred)\n",
        "    xgb_f1 = f1_score(y_test, xgb_pred)\n",
        "    \n",
        "    print(f\"XGBoost Test Accuracy: {xgb_acc:.4f}\")\n",
        "    print(f\"XGBoost Test F1 Score: {xgb_f1:.4f}\")\n",
        "    \n",
        "    # Feature importance\n",
        "    xgb_importance = xgb_model.feature_importances_\n",
        "    xgb_importance_df = pd.DataFrame({\n",
        "        'Feature': feature_names,\n",
        "        'Importance': xgb_importance\n",
        "    }).sort_values('Importance', ascending=False)\n",
        "    \n",
        "    print(\"\\nXGBoost Feature Importance:\")\n",
        "    print(xgb_importance_df)\n",
        "    \n",
        "except ImportError:\n",
        "    print(\"⚠️ XGBoost not installed. Skipping XGBoost baseline.\")\n",
        "    print(\"Install with: pip install xgboost\")\n",
        "    xgb_acc = None\n",
        "    xgb_f1 = None"
    ]
})

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 8.3 Model Comparison"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Compare all models\n",
        "comparison_data = {\n",
        "    'Model': ['Transformer', 'MLP', 'XGBoost'],\n",
        "    'Accuracy': [accuracy, mlp_best_acc, xgb_acc if xgb_acc else 0],\n",
        "    'F1 Score': [f1, 0, xgb_f1 if xgb_f1 else 0],  # не считали F1 для MLP\n",
        "    'Parameters': [trainable_params, \n",
        "                   sum(p.numel() for p in mlp.parameters()),\n",
        "                   0]  # XGBoost не имеет градиентных параметров\n",
        "}\n",
        "\n",
        "comparison_df = pd.DataFrame(comparison_data)\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"MODEL COMPARISON\")\n",
        "print(\"=\"*60)\n",
        "print(comparison_df.to_string(index=False))\n",
        "print(\"=\"*60)\n",
        "\n",
        "# Визуализация\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Accuracy comparison\n",
        "axes[0].bar(comparison_df['Model'], comparison_df['Accuracy'], \n",
        "           color=['steelblue', 'orange', 'green'])\n",
        "axes[0].set_title('Model Accuracy Comparison', fontsize=16, fontweight='bold')\n",
        "axes[0].set_ylabel('Accuracy', fontsize=12)\n",
        "axes[0].set_ylim([0.7, 0.9])\n",
        "axes[0].grid(alpha=0.3, axis='y')\n",
        "for i, v in enumerate(comparison_df['Accuracy']):\n",
        "    axes[0].text(i, v + 0.01, f\"{v:.3f}\", ha='center', fontweight='bold')\n",
        "\n",
        "# Parameters comparison\n",
        "valid_params = [(m, p) for m, p in zip(comparison_df['Model'], comparison_df['Parameters']) if p > 0]\n",
        "if valid_params:\n",
        "    models, params = zip(*valid_params)\n",
        "    axes[1].bar(models, params, color=['steelblue', 'orange'])\n",
        "    axes[1].set_title('Model Size (Parameters)', fontsize=16, fontweight='bold')\n",
        "    axes[1].set_ylabel('# Parameters', fontsize=12)\n",
        "    axes[1].grid(alpha=0.3, axis='y')\n",
        "    for i, (m, p) in enumerate(valid_params):\n",
        "        axes[1].text(i, p + 500, f\"{p:,}\", ha='center', fontweight='bold')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n📊 Выводы:\")\n",
        "print(\"  - Transformer показывает competitive результаты с baselines\")\n",
        "print(\"  - XGBoost по-прежнему силен на табличных данных (особенно на маленьких)\")\n",
        "print(\"  - Transformer дает бонус: attention weights для interpretability\")\n",
        "print(\"  - На больших датасетах Transformer может превзойти tree-based методы\")"
    ]
})

# ============================================================================
# CONCLUSIONS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 🎓 Итоги и Выводы\n",
        "\n",
        "### Что мы изучили\n",
        "\n",
        "#### 1. Self-Attention Mechanism\n",
        "- ✅ **Query, Key, Value**: как работает attention\n",
        "- ✅ **Scaled Dot-Product**: $\\text{Attention}(Q,K,V) = \\text{softmax}(QK^T/\\sqrt{d_k})V$\n",
        "- ✅ **Parallelization**: все вычисления параллельны (vs RNN sequential)\n",
        "- ✅ **Long-range dependencies**: прямые связи O(1) path length\n",
        "\n",
        "#### 2. Multi-Head Attention\n",
        "- ✅ **Multiple perspectives**: разные heads учат разные паттерны\n",
        "- ✅ **Ensemble effect**: внутри одного слоя\n",
        "- ✅ **Richer representations**: $h$ параллельных attention mechanisms\n",
        "\n",
        "#### 3. Positional Encoding\n",
        "- ✅ **Sinusoidal**: для sequences (NLP, time series)\n",
        "- ✅ **Learnable**: для табличных данных (нет естественного порядка)\n",
        "- ✅ **Решает permutation invariance**: модель знает позиции\n",
        "\n",
        "#### 4. Transformer Encoder\n",
        "- ✅ **Architecture**: Multi-Head Attention → Add&Norm → FFN → Add&Norm\n",
        "- ✅ **Residual connections**: помогают gradient flow\n",
        "- ✅ **Layer Normalization**: стабилизирует обучение\n",
        "- ✅ **Feed-Forward Network**: позиционно-независимые трансформации\n",
        "\n",
        "#### 5. Применение к Табличным Данным\n",
        "- ✅ **Feature embedding**: Linear projection для каждой feature\n",
        "- ✅ **Feature interactions**: автоматически через attention\n",
        "- ✅ **Interpretability**: attention weights показывают важность\n",
        "- ✅ **Competitive performance**: сравнимо с XGBoost на Titanic\n",
        "\n",
        "---\n",
        "\n",
        "### Ключевые преимущества Transformers\n",
        "\n",
        "| Aspect | RNN/LSTM | Transformer |\n",
        "|--------|----------|-------------|\n",
        "| **Processing** | Sequential | Parallel |\n",
        "| **Long-range deps** | O(n) path | O(1) path |\n",
        "| **Training speed** | Slow | Fast (GPU) |\n",
        "| **Interpretability** | Hard | Attention weights |\n",
        "| **Scalability** | Limited | Excellent |\n",
        "| **SOTA results** | 2014-2017 | 2017+ |\n",
        "\n",
        "---\n",
        "\n",
        "### Когда использовать Transformers для табличных данных?\n",
        "\n",
        "**✅ Хорошо работают когда:**\n",
        "- Большие датасеты (>10k samples)\n",
        "- Много categorical features\n",
        "- Сложные feature interactions\n",
        "- Нужна interpretability\n",
        "- Доступен pre-training на похожих данных\n",
        "\n",
        "**❌ Могут уступать tree-based методам когда:**\n",
        "- Маленькие датасеты (<1k samples)\n",
        "- Простые feature interactions\n",
        "- Только numerical features\n",
        "- Нужна максимальная производительность без тюнинга\n",
        "\n",
        "---\n",
        "\n",
        "### Что дальше?\n",
        "\n",
        "**Phase 4, Step 2: TabTransformer**\n",
        "- Специальные embeddings для категориальных features\n",
        "- Contextual embeddings через Transformer\n",
        "- Лучшая производительность на табличных данных\n",
        "\n",
        "**Phase 4, Step 3: Advanced Architectures**\n",
        "- FT-Transformer (Feature Tokenizer)\n",
        "- SAINT (Self-Attention and Intersample Attention)\n",
        "- TabNet (attention-based табличная архитектура)\n",
        "- Temporal Fusion Transformer (для time series)\n",
        "\n",
        "**Phase 5: Transfer Learning & Pre-training**\n",
        "- Pre-training на больших датасетах\n",
        "- Fine-tuning на целевой задаче\n",
        "- Self-supervised learning\n",
        "\n",
        "---\n",
        "\n",
        "### Дополнительные ресурсы\n",
        "\n",
        "**Papers:**\n",
        "- \"Attention is All You Need\" (Vaswani et al., 2017) - оригинальная статья\n",
        "- \"TabTransformer\" (Huang et al., 2020) - Transformer для табличных данных\n",
        "- \"Revisiting Deep Learning Models for Tabular Data\" (Gorishniy et al., 2021)\n",
        "\n",
        "**Tutorials:**\n",
        "- The Illustrated Transformer (Jay Alammar)\n",
        "- Annotated Transformer (Harvard NLP)\n",
        "\n",
        "---\n",
        "\n",
        "## 🎉 Поздравляем!\n",
        "\n",
        "Вы освоили основы Transformer архитектуры!\n",
        "\n",
        "Теперь вы понимаете:\n",
        "- 🧠 Как работает Self-Attention\n",
        "- 🔮 Почему Transformers революционизировали ML\n",
        "- 📊 Как применять Transformers к табличным данным\n",
        "- 🔍 Как интерпретировать модель через attention weights\n",
        "\n",
        "**Следующий шаг:** TabTransformer для улучшенной работы с категориальными features!\n"
    ]
})

# Сохраняем
notebook['cells'] = cells

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f'✅ Part 4 добавлена в: {notebook_path}')
print(f'Всего ячеек: {len(cells)}')
print('Notebook ЗАВЕРШЕН!')
print('\nСтруктура:')
print('  Part 1: Introduction, Theory, Scaled Dot-Product Attention')
print('  Part 2: Multi-Head Attention, Positional Encoding')
print('  Part 3: Transformer Encoder, Titanic Dataset')
print('  Part 4: Training, Evaluation, Attention Viz, Comparisons, Conclusions')
