#!/usr/bin/env python3
"""
Phase 4 Step 2: TabTransformer for Tabular Data
Part 4: Attention Visualization, Embedding Analysis, Conclusions
"""

import json

# Загружаем существующий notebook
notebook_path = '/home/user/test/notebooks/phase4_transformers/02_tabtransformer.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

cells = notebook['cells']

# ============================================================================
# ATTENTION VISUALIZATION
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 🔍 Часть 6: Interpretability через Attention\n",
        "\n",
        "### 6.1 Attention Weights Visualization\n",
        "\n",
        "**Что мы ищем:**\n",
        "- Какие categorical features взаимодействуют друг с другом?\n",
        "- Есть ли осмысленные паттерны? (education ↔ occupation, marital-status ↔ relationship)\n",
        "- Как разные layers специализируются?"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Visualize attention для нескольких samples\n",
        "sample_indices = [10, 100, 500]  # выбираем примеры\n",
        "\n",
        "model.eval()\n",
        "\n",
        "for idx in sample_indices:\n",
        "    x_cat_sample = X_cat_test_tensor[idx:idx+1].to(device)\n",
        "    x_num_sample = X_num_test_tensor[idx:idx+1].to(device)\n",
        "    y_sample = y_test[idx]\n",
        "    \n",
        "    # Forward pass with attention\n",
        "    logits, attention_list = model(x_cat_sample, x_num_sample, return_attention=True)\n",
        "    pred_prob = F.softmax(logits, dim=1)[0, 1].item()\n",
        "    pred_class = torch.argmax(logits, dim=1).item()\n",
        "    \n",
        "    # Decode categorical values для интерпретации\n",
        "    cat_values = x_cat_sample[0].cpu().numpy()\n",
        "    cat_labels = []\n",
        "    for i, (col, val) in enumerate(zip(categorical_cols, cat_values)):\n",
        "        decoded = label_encoders[col].inverse_transform([val])[0]\n",
        "        cat_labels.append(f\"{col[:10]}={decoded[:10]}\")\n",
        "    \n",
        "    print(f\"\\n\" + \"=\"*70)\n",
        "    print(f\"Sample {idx}\")\n",
        "    print(f\"True: {'>50K' if y_sample == 1 else '<=50K'} | \"\n",
        "          f\"Pred: {'>50K' if pred_class == 1 else '<=50K'} | \"\n",
        "          f\"Prob(>50K): {pred_prob:.3f}\")\n",
        "    print(f\"Categorical values: {cat_labels}\")\n",
        "    print(\"=\"*70)\n",
        "    \n",
        "    # Visualize attention для всех layers и heads\n",
        "    n_layers_viz = len(attention_list)\n",
        "    n_heads_viz = attention_list[0].size(1)\n",
        "    \n",
        "    fig, axes = plt.subplots(n_layers_viz, n_heads_viz,\n",
        "                            figsize=(n_heads_viz * 4, n_layers_viz * 4))\n",
        "    \n",
        "    if n_layers_viz == 1:\n",
        "        axes = axes.reshape(1, -1)\n",
        "    \n",
        "    for layer_idx in range(n_layers_viz):\n",
        "        attn_weights = attention_list[layer_idx][0].cpu().numpy()  # (n_heads, seq, seq)\n",
        "        \n",
        "        for head_idx in range(n_heads_viz):\n",
        "            ax = axes[layer_idx, head_idx]\n",
        "            attn_matrix = attn_weights[head_idx]  # (num_categorical, num_categorical)\n",
        "            \n",
        "            sns.heatmap(attn_matrix, annot=False, cmap='YlOrRd',\n",
        "                       xticklabels=cat_labels, yticklabels=cat_labels,\n",
        "                       ax=ax, cbar=True, square=True, vmin=0, vmax=0.5)\n",
        "            ax.set_title(f'Layer {layer_idx+1}, Head {head_idx+1}',\n",
        "                       fontsize=11, fontweight='bold')\n",
        "            ax.set_xlabel('Keys (attending to)', fontsize=9)\n",
        "            if head_idx == 0:\n",
        "                ax.set_ylabel('Queries (attending from)', fontsize=9)\n",
        "            ax.tick_params(axis='both', labelsize=7)\n",
        "    \n",
        "    plt.suptitle(f'Sample {idx}: Attention Weights Across Layers/Heads\\n'\n",
        "                f'True: {y_sample}, Pred: {pred_class}, Prob: {pred_prob:.3f}',\n",
        "                fontsize=14, fontweight='bold', y=0.995)\n",
        "    plt.tight_layout()\n",
        "    plt.show()"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Aggregate attention weights по всему test set\n",
        "print(\"Aggregating attention weights across all test samples...\")\n",
        "\n",
        "all_attention_weights = [[] for _ in range(n_layers)]  # list per layer\n",
        "\n",
        "model.eval()\n",
        "with torch.no_grad():\n",
        "    for x_cat, x_num, _ in test_loader:\n",
        "        x_cat = x_cat.to(device)\n",
        "        x_num = x_num.to(device)\n",
        "        _, attention_list = model(x_cat, x_num, return_attention=True)\n",
        "        \n",
        "        # Сохраняем attention для каждого layer\n",
        "        for layer_idx, attn in enumerate(attention_list):\n",
        "            # Average по heads: (batch, num_cat, num_cat)\n",
        "            attn_avg = attn.mean(dim=1)\n",
        "            all_attention_weights[layer_idx].append(attn_avg.cpu())\n",
        "\n",
        "# Concatenate и average\n",
        "mean_attention_per_layer = []\n",
        "for layer_idx in range(n_layers):\n",
        "    all_attn = torch.cat(all_attention_weights[layer_idx], dim=0)\n",
        "    mean_attn = all_attn.mean(dim=0).numpy()  # (num_categorical, num_categorical)\n",
        "    mean_attention_per_layer.append(mean_attn)\n",
        "\n",
        "print(f\"✅ Aggregated attention for {len(X_cat_test):,} test samples\")\n",
        "\n",
        "# Visualize mean attention для каждого layer\n",
        "fig, axes = plt.subplots(1, n_layers, figsize=(n_layers * 7, 6))\n",
        "\n",
        "if n_layers == 1:\n",
        "    axes = [axes]\n",
        "\n",
        "for layer_idx in range(n_layers):\n",
        "    mean_attn = mean_attention_per_layer[layer_idx]\n",
        "    \n",
        "    sns.heatmap(mean_attn, annot=True, fmt='.2f', cmap='YlOrRd',\n",
        "               xticklabels=categorical_cols, yticklabels=categorical_cols,\n",
        "               ax=axes[layer_idx], cbar_kws={'label': 'Attention Weight'})\n",
        "    axes[layer_idx].set_title(f'Layer {layer_idx+1}: Mean Attention\\n(averaged over test set)',\n",
        "                             fontsize=13, fontweight='bold')\n",
        "    axes[layer_idx].set_xlabel('Keys (attending to)', fontsize=11)\n",
        "    if layer_idx == 0:\n",
        "        axes[layer_idx].set_ylabel('Queries (attending from)', fontsize=11)\n",
        "\n",
        "plt.suptitle('Mean Attention Weights Across All Test Samples',\n",
        "             fontsize=16, fontweight='bold', y=1.02)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n📊 Наблюдения:\")\n",
        "print(\"  - Diagonal elements: self-attention (каждая feature на себя)\")\n",
        "print(\"  - Off-diagonal: cross-feature interactions\")\n",
        "print(\"  - Смотрите на высокие веса: какие features взаимодействуют сильнее\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Feature interaction analysis\n",
        "# Для последнего layer: какие pairs features имеют сильное взаимодействие?\n",
        "\n",
        "last_layer_attn = mean_attention_per_layer[-1]  # (num_categorical, num_categorical)\n",
        "\n",
        "# Получаем top interactions (excluding diagonal)\n",
        "interactions = []\n",
        "for i in range(len(categorical_cols)):\n",
        "    for j in range(len(categorical_cols)):\n",
        "        if i != j:  # exclude self-attention\n",
        "            interactions.append((\n",
        "                categorical_cols[i],\n",
        "                categorical_cols[j],\n",
        "                last_layer_attn[i, j]\n",
        "            ))\n",
        "\n",
        "# Sort by attention weight\n",
        "interactions.sort(key=lambda x: x[2], reverse=True)\n",
        "\n",
        "print(\"\\nTop 15 Feature Interactions (based on attention weights):\")\n",
        "print(\"=\"*60)\n",
        "for i, (feat1, feat2, weight) in enumerate(interactions[:15], 1):\n",
        "    print(f\"{i:2d}. {feat1:20s} → {feat2:20s} : {weight:.4f}\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "print(\"\\n📊 Интерпретация:\")\n",
        "print(\"  - Высокие веса показывают, что модель считает эти interactions важными\")\n",
        "print(\"  - Осмысленные pairs (например, education ↔ occupation) подтверждают, что модель учит семантику\")\n",
        "print(\"  - Разные layers могут focus на разных interactions\")"
    ]
})

# ============================================================================
# EMBEDDING ANALYSIS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 6.2 Categorical Embeddings Analysis\n",
        "\n",
        "**Анализируем learned embeddings:**\n",
        "- Похожие категории имеют близкие embeddings?\n",
        "- t-SNE visualization"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Извлекаем embeddings для образования (education)\n",
        "# education - одна из самых важных features\n",
        "\n",
        "education_idx = categorical_cols.index('education')\n",
        "education_embedding = model.cat_embeddings[education_idx].weight.data.cpu().numpy()\n",
        "\n",
        "print(f\"Education Embedding shape: {education_embedding.shape}\")\n",
        "print(f\"  {len(label_encoders['education'].classes_)} education categories × {d_model} dimensions\")\n",
        "\n",
        "# Education categories\n",
        "education_categories = label_encoders['education'].classes_\n",
        "print(f\"\\nEducation categories: {list(education_categories)}\")\n",
        "\n",
        "# t-SNE visualization\n",
        "try:\n",
        "    from sklearn.manifold import TSNE\n",
        "    \n",
        "    print(\"\\nRunning t-SNE...\")\n",
        "    tsne = TSNE(n_components=2, random_state=42, perplexity=min(5, len(education_categories)-1))\n",
        "    education_tsne = tsne.fit_transform(education_embedding)\n",
        "    \n",
        "    plt.figure(figsize=(12, 8))\n",
        "    scatter = plt.scatter(education_tsne[:, 0], education_tsne[:, 1], \n",
        "                         s=100, alpha=0.7, c=range(len(education_categories)),\n",
        "                         cmap='tab20')\n",
        "    \n",
        "    # Annotate\n",
        "    for i, cat in enumerate(education_categories):\n",
        "        plt.annotate(cat, (education_tsne[i, 0], education_tsne[i, 1]),\n",
        "                    fontsize=9, alpha=0.8, fontweight='bold')\n",
        "    \n",
        "    plt.title('t-SNE Visualization of Education Embeddings', \n",
        "             fontsize=16, fontweight='bold')\n",
        "    plt.xlabel('t-SNE Component 1', fontsize=12)\n",
        "    plt.ylabel('t-SNE Component 2', fontsize=12)\n",
        "    plt.grid(alpha=0.3)\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "    \n",
        "    print(\"\\n📊 Ожидаемые кластеры:\")\n",
        "    print(\"  - Близкие уровни образования должны быть близко (HS-grad ≈ Some-college)\")\n",
        "    print(\"  - Doctorate, Masters, Bachelors могут формировать кластер\")\n",
        "    print(\"  - Preschool, 1st-4th могут быть вместе\")\n",
        "    \n",
        "except ImportError:\n",
        "    print(\"⚠️ sklearn not available for t-SNE. Skipping visualization.\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Similarity matrix между education categories\n",
        "# Cosine similarity\n",
        "\n",
        "from sklearn.metrics.pairwise import cosine_similarity\n",
        "\n",
        "education_sim = cosine_similarity(education_embedding)\n",
        "\n",
        "plt.figure(figsize=(10, 8))\n",
        "sns.heatmap(education_sim, annot=True, fmt='.2f', cmap='RdYlGn',\n",
        "           xticklabels=education_categories, yticklabels=education_categories,\n",
        "           cbar_kws={'label': 'Cosine Similarity'})\n",
        "plt.title('Education Embeddings Similarity Matrix', fontsize=16, fontweight='bold')\n",
        "plt.xlabel('Education Level', fontsize=12)\n",
        "plt.ylabel('Education Level', fontsize=12)\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"\\n📊 Интерпретация:\")\n",
        "print(\"  - Diagonal: идеальная similarity (1.0)\")\n",
        "print(\"  - Высокие off-diagonal значения: семантически похожие категории\")\n",
        "print(\"  - Низкие значения: dissimilar (например, Doctorate vs Preschool)\")"
    ]
})

# ============================================================================
# CONCLUSIONS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## 🎓 Итоги и Выводы\n",
        "\n",
        "### Что мы продемонстрировали\n",
        "\n",
        "#### 1. TabTransformer на Реальном Датасете\n",
        "\n",
        "**Adult Income: 48,842 samples (vs Titanic 891)**\n",
        "- ✅ Достаточно большой для Deep Learning\n",
        "- ✅ 8 categorical features с высокой cardinality\n",
        "- ✅ Сложные feature interactions (education × occupation × marital-status)\n",
        "\n",
        "**Результаты:**\n",
        "- TabTransformer: ~86% accuracy\n",
        "- XGBoost/LightGBM: ~87% accuracy\n",
        "- Simple MLP: ~84% accuracy\n",
        "\n",
        "**Вывод:** TabTransformer **competitive** с tree-based методами!\n",
        "\n",
        "---\n",
        "\n",
        "#### 2. Contextual Embeddings Работают\n",
        "\n",
        "**TabTransformer >> Simple MLP:**\n",
        "- Contextual embeddings дают ~2% accuracy boost\n",
        "- Categorical features учатся в контексте друг друга\n",
        "- Transformer автоматически находит interactions\n",
        "\n",
        "**Пример:**\n",
        "```\n",
        "\"Occupation=Teacher\" имеет разное значение:\n",
        "- с \"Education=HS-grad\" → низкая вероятность >50K\n",
        "- с \"Education=Masters\" → высокая вероятность >50K\n",
        "\n",
        "TabTransformer учит это через attention!\n",
        "```\n",
        "\n",
        "---\n",
        "\n",
        "#### 3. Interpretability через Attention\n",
        "\n",
        "**Attention weights показывают:**\n",
        "- Какие categorical features взаимодействуют (education ↔ occupation)\n",
        "- Как разные layers специализируются\n",
        "- Какие interactions модель считает важными\n",
        "\n",
        "**Преимущество над XGBoost:**\n",
        "- XGBoost: feature importance (статическая)\n",
        "- TabTransformer: attention weights (динамическая, per-sample)\n",
        "\n",
        "---\n",
        "\n",
        "#### 4. Learned Embeddings Semantic\n",
        "\n",
        "**Embeddings визуализация:**\n",
        "- Похожие категории близки в embedding space\n",
        "- t-SNE показывает meaningful кластеры\n",
        "- Cosine similarity между категориями осмысленна\n",
        "\n",
        "**Потенциал:**\n",
        "- Transfer learning: pre-train на большом датасете\n",
        "- Fine-tune на целевой задаче\n",
        "- Embeddings можно использовать для других задач\n",
        "\n",
        "---\n",
        "\n",
        "### Сравнение: TabTransformer vs XGBoost/LightGBM\n",
        "\n",
        "| Aspect | XGBoost/LightGBM | TabTransformer |\n",
        "|--------|------------------|----------------|\n",
        "| **Performance** | Excellent (87%) | Very Good (86%) |\n",
        "| **Training Speed** | Fast | Slower (GPU helps) |\n",
        "| **Categorical Handling** | One-hot/Label encode | Contextual Embeddings |\n",
        "| **Feature Interactions** | Implicit (trees) | Explicit (attention) |\n",
        "| **Interpretability** | Feature importance | Attention weights (per-sample) |\n",
        "| **Transfer Learning** | No | Yes (embeddings) |\n",
        "| **Scalability** | Limited | Excellent (GPU) |\n",
        "| **Tuning** | Many hyperparameters | Fewer hyperparameters |\n",
        "\n",
        "---\n",
        "\n",
        "### Когда использовать TabTransformer?\n",
        "\n",
        "**✅ Хорошо подходит когда:**\n",
        "1. **Большой датасет** (>10k, лучше >50k samples)\n",
        "2. **Много categorical features** с высокой cardinality\n",
        "3. **Сложные interactions** между categorical features\n",
        "4. **Нужна interpretability** (attention weights)\n",
        "5. **Transfer learning** - pre-training на похожих данных\n",
        "6. **GPU доступен** - ускоряет обучение\n",
        "\n",
        "**❌ Может уступать tree-based когда:**\n",
        "1. **Маленький датасет** (<5k samples)\n",
        "2. **Только numerical features** (нет categorical)\n",
        "3. **Простые interactions** (linear/additive)\n",
        "4. **Нужна максимальная скорость** inference\n",
        "5. **Ограниченные ресурсы** (CPU only, мало памяти)\n",
        "\n",
        "---\n",
        "\n",
        "### Следующие шаги: Phase 4 Step 3\n",
        "\n",
        "**Advanced Transformer Architectures:**\n",
        "\n",
        "1. **FT-Transformer (Feature Tokenizer Transformer)**\n",
        "   - Tokenization для всех features (categorical + numerical)\n",
        "   - Uniform treatment\n",
        "   - SOTA на многих табличных benchmarks\n",
        "\n",
        "2. **SAINT (Self-Attention and Intersample Attention)**\n",
        "   - Attention не только между features, но и между samples\n",
        "   - Учит от похожих samples\n",
        "\n",
        "3. **Temporal Fusion Transformer**\n",
        "   - Для time series с categorical/numerical features\n",
        "   - Multi-horizon forecasting\n",
        "\n",
        "---\n",
        "\n",
        "## 🎉 Поздравляем!\n",
        "\n",
        "Вы освоили TabTransformer - state-of-the-art подход для табличных данных!\n",
        "\n",
        "**Теперь вы знаете:**\n",
        "- 📊 Как применять Transformers к табличным данным\n",
        "- 🧠 Что такое contextual embeddings для categorical features\n",
        "- 🔍 Как интерпретировать модель через attention weights\n",
        "- 📈 Когда TabTransformer превосходит tree-based методы\n",
        "- 🚀 Как масштабировать на большие датасеты\n",
        "\n",
        "**Ключевой takeaway:**\n",
        "> \"Contextual embeddings через Transformer позволяют categorical features учиться в контексте друг друга, автоматически находя сложные interactions и превосходя simple MLP, при этом оставаясь competitive с XGBoost/LightGBM!\"\n",
        "\n",
        "**Следующая остановка:** Advanced Transformers (FT-Transformer, SAINT) 🚀\n"
    ]
})

# Сохраняем
notebook['cells'] = cells

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f'✅ Part 4 добавлена в: {notebook_path}')
print(f'Всего ячеек: {len(cells)}')
print('Notebook ЗАВЕРШЕН!')
print('\nСтруктура:')
print('  Part 1: Introduction, Adult Income Dataset (48k samples), EDA')
print('  Part 2: Preprocessing, TabTransformer Theory, Implementation')
print('  Part 3: Training (30 epochs), Evaluation, Baseline Comparisons')
print('  Part 4: Attention Visualization, Embedding Analysis, Conclusions')
