#!/usr/bin/env python3
"""
Phase 3 BONUS: Real-world Financial Pattern Recognition
Part 2: Comprehensive Feature Engineering
"""

import json

# Загружаем существующий ноутбук
notebook_path = '/home/user/test/notebooks/phase3_temporal_rnn/bonus_financial_patterns.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

cells = notebook['cells']

# ============================================================================
# FEATURE ENGINEERING - TECHNICAL INDICATORS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🔧 Часть 2: Feature Engineering\n",
        "\n",
        "### 2.1 Технические индикаторы (20+ фич)\n",
        "\n",
        "**Категории индикаторов:**\n",
        "1. **Trend (Трендовые):** SMA, EMA, MACD, ADX\n",
        "2. **Momentum (Импульс):** RSI, Stochastic, ROC, Williams %R\n",
        "3. **Volatility (Волатильность):** Bollinger Bands, ATR, Keltner Channel\n",
        "4. **Volume (Объем):** OBV, Volume SMA, VWAP\n",
        "\n",
        "**Используем библиотеку `ta` (Technical Analysis Library in Python)**"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Копируем данные для feature engineering\n",
        "df_features = df.copy()\n",
        "\n",
        "print(\"Создание технических индикаторов...\")\n",
        "\n",
        "# ============================================================================\n",
        "# 1. TREND INDICATORS\n",
        "# ============================================================================\n",
        "\n",
        "# Simple Moving Averages\n",
        "df_features['SMA_20'] = ta.trend.sma_indicator(df['Close'], window=20)\n",
        "df_features['SMA_50'] = ta.trend.sma_indicator(df['Close'], window=50)\n",
        "df_features['SMA_200'] = ta.trend.sma_indicator(df['Close'], window=200)\n",
        "\n",
        "# Exponential Moving Averages\n",
        "df_features['EMA_12'] = ta.trend.ema_indicator(df['Close'], window=12)\n",
        "df_features['EMA_26'] = ta.trend.ema_indicator(df['Close'], window=26)\n",
        "\n",
        "# MACD\n",
        "macd = ta.trend.MACD(df['Close'])\n",
        "df_features['MACD'] = macd.macd()\n",
        "df_features['MACD_signal'] = macd.macd_signal()\n",
        "df_features['MACD_diff'] = macd.macd_diff()\n",
        "\n",
        "# ADX (Average Directional Index) - strength of trend\n",
        "adx = ta.trend.ADXIndicator(df['High'], df['Low'], df['Close'], window=14)\n",
        "df_features['ADX'] = adx.adx()\n",
        "df_features['ADX_pos'] = adx.adx_pos()\n",
        "df_features['ADX_neg'] = adx.adx_neg()\n",
        "\n",
        "print(\"✅ Trend indicators: SMA, EMA, MACD, ADX\")\n",
        "\n",
        "# ============================================================================\n",
        "# 2. MOMENTUM INDICATORS\n",
        "# ============================================================================\n",
        "\n",
        "# RSI (Relative Strength Index)\n",
        "df_features['RSI'] = ta.momentum.rsi(df['Close'], window=14)\n",
        "\n",
        "# Stochastic Oscillator\n",
        "stoch = ta.momentum.StochasticOscillator(\n",
        "    df['High'], df['Low'], df['Close'], window=14, smooth_window=3\n",
        ")\n",
        "df_features['Stoch_K'] = stoch.stoch()\n",
        "df_features['Stoch_D'] = stoch.stoch_signal()\n",
        "\n",
        "# ROC (Rate of Change)\n",
        "df_features['ROC'] = ta.momentum.roc(df['Close'], window=12)\n",
        "\n",
        "# Williams %R\n",
        "df_features['Williams_R'] = ta.momentum.williams_r(\n",
        "    df['High'], df['Low'], df['Close'], lbp=14\n",
        ")\n",
        "\n",
        "print(\"✅ Momentum indicators: RSI, Stochastic, ROC, Williams %R\")\n",
        "\n",
        "# ============================================================================\n",
        "# 3. VOLATILITY INDICATORS\n",
        "# ============================================================================\n",
        "\n",
        "# Bollinger Bands\n",
        "bollinger = ta.volatility.BollingerBands(df['Close'], window=20, window_dev=2)\n",
        "df_features['BB_upper'] = bollinger.bollinger_hband()\n",
        "df_features['BB_middle'] = bollinger.bollinger_mavg()\n",
        "df_features['BB_lower'] = bollinger.bollinger_lband()\n",
        "df_features['BB_width'] = bollinger.bollinger_wband()\n",
        "df_features['BB_pband'] = bollinger.bollinger_pband()  # position in band\n",
        "\n",
        "# ATR (Average True Range)\n",
        "df_features['ATR'] = ta.volatility.average_true_range(\n",
        "    df['High'], df['Low'], df['Close'], window=14\n",
        ")\n",
        "\n",
        "# Keltner Channel\n",
        "keltner = ta.volatility.KeltnerChannel(df['High'], df['Low'], df['Close'], window=20)\n",
        "df_features['Keltner_upper'] = keltner.keltner_channel_hband()\n",
        "df_features['Keltner_lower'] = keltner.keltner_channel_lband()\n",
        "\n",
        "print(\"✅ Volatility indicators: Bollinger Bands, ATR, Keltner\")\n",
        "\n",
        "# ============================================================================\n",
        "# 4. VOLUME INDICATORS\n",
        "# ============================================================================\n",
        "\n",
        "# OBV (On-Balance Volume)\n",
        "df_features['OBV'] = ta.volume.on_balance_volume(df['Close'], df['Volume'])\n",
        "\n",
        "# Volume SMA\n",
        "df_features['Volume_SMA_20'] = df['Volume'].rolling(window=20).mean()\n",
        "\n",
        "# Volume ratio\n",
        "df_features['Volume_ratio'] = df['Volume'] / df_features['Volume_SMA_20']\n",
        "\n",
        "print(\"✅ Volume indicators: OBV, Volume SMA, Volume ratio\")\n",
        "\n",
        "print(f\"\\n📊 Всего индикаторов создано: {len(df_features.columns) - len(df.columns)}\")"
    ]
})

# ============================================================================
# CUSTOM FEATURES FOR CHART PATTERNS
# ============================================================================

cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 2.2 Кастомные фичи для графических паттернов\n",
        "\n",
        "**Цель:** Создать фичи, которые \"подсказывают\" нейросети о графических паттернах.\n",
        "\n",
        "**Подход:**\n",
        "1. Мы визуально знаем паттерн (например, \"голова-плечи\")\n",
        "2. Формализуем ключевые характеристики через фичи\n",
        "3. Сеть учится комбинировать эти фичи\n",
        "\n",
        "**Категории:**\n",
        "- **Pivot points** (локальные максимумы/минимумы)\n",
        "- **Support/Resistance** levels\n",
        "- **Pattern-specific** features\n",
        "- **Price action** features"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ============================================================================\n",
        "# PIVOT POINTS (локальные max/min)\n",
        "# ============================================================================\n",
        "\n",
        "def find_pivots(df, window=5):\n",
        "    \"\"\"\n",
        "    Находит локальные максимумы и минимумы\n",
        "    \n",
        "    Returns:\n",
        "        pivot_high: 1 если локальный max, 0 иначе\n",
        "        pivot_low: 1 если локальный min, 0 иначе\n",
        "    \"\"\"\n",
        "    pivot_high = []\n",
        "    pivot_low = []\n",
        "    \n",
        "    for i in range(len(df)):\n",
        "        if i < window or i >= len(df) - window:\n",
        "            pivot_high.append(0)\n",
        "            pivot_low.append(0)\n",
        "            continue\n",
        "        \n",
        "        # Локальный максимум\n",
        "        is_high = all(df['High'].iloc[i] > df['High'].iloc[i-j] \n",
        "                     for j in range(1, window+1))\n",
        "        is_high = is_high and all(df['High'].iloc[i] > df['High'].iloc[i+j] \n",
        "                                 for j in range(1, window+1))\n",
        "        \n",
        "        # Локальный минимум\n",
        "        is_low = all(df['Low'].iloc[i] < df['Low'].iloc[i-j] \n",
        "                    for j in range(1, window+1))\n",
        "        is_low = is_low and all(df['Low'].iloc[i] < df['Low'].iloc[i+j] \n",
        "                               for j in range(1, window+1))\n",
        "        \n",
        "        pivot_high.append(1 if is_high else 0)\n",
        "        pivot_low.append(1 if is_low else 0)\n",
        "    \n",
        "    return pivot_high, pivot_low\n",
        "\n",
        "print(\"Поиск pivot points...\")\n",
        "pivot_high, pivot_low = find_pivots(df_features, window=5)\n",
        "df_features['Pivot_High'] = pivot_high\n",
        "df_features['Pivot_Low'] = pivot_low\n",
        "\n",
        "# Количество пивотов в окне (для Head & Shoulders)\n",
        "df_features['Pivot_High_count_20'] = df_features['Pivot_High'].rolling(window=20).sum()\n",
        "df_features['Pivot_Low_count_20'] = df_features['Pivot_Low'].rolling(window=20).sum()\n",
        "\n",
        "print(f\"✅ Pivot points: найдено {df_features['Pivot_High'].sum()} максимумов, \"\n",
        "      f\"{df_features['Pivot_Low'].sum()} минимумов\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ============================================================================\n",
        "# PRICE ACTION FEATURES\n",
        "# ============================================================================\n",
        "\n",
        "# Candle body and shadows\n",
        "df_features['Candle_body'] = abs(df['Close'] - df['Open'])\n",
        "df_features['Upper_shadow'] = df['High'] - df[['Open', 'Close']].max(axis=1)\n",
        "df_features['Lower_shadow'] = df[['Open', 'Close']].min(axis=1) - df['Low']\n",
        "df_features['Candle_range'] = df['High'] - df['Low']\n",
        "\n",
        "# Body ratio (для doji и других паттернов)\n",
        "df_features['Body_ratio'] = df_features['Candle_body'] / (df_features['Candle_range'] + 1e-10)\n",
        "\n",
        "# Price momentum (относительно SMA)\n",
        "df_features['Price_above_SMA20'] = (df['Close'] > df_features['SMA_20']).astype(int)\n",
        "df_features['Price_above_SMA50'] = (df['Close'] > df_features['SMA_50']).astype(int)\n",
        "df_features['Price_vs_SMA20'] = df['Close'] / df_features['SMA_20'] - 1\n",
        "\n",
        "# Distance from recent high/low (для пробоев)\n",
        "df_features['Distance_from_20H'] = df['Close'] / df['High'].rolling(20).max() - 1\n",
        "df_features['Distance_from_20L'] = df['Close'] / df['Low'].rolling(20).min() - 1\n",
        "\n",
        "print(\"✅ Price action features создан\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ============================================================================\n",
        "# PATTERN-SPECIFIC FEATURES\n",
        "# ============================================================================\n",
        "\n",
        "# 1. HEAD & SHOULDERS features\n",
        "# Симметрия пиков (левое плечо ≈ правое плечо)\n",
        "def calculate_peak_symmetry(df, window=30):\n",
        "    \"\"\"Измеряет симметрию недавних пиков\"\"\"\n",
        "    symmetry = []\n",
        "    for i in range(len(df)):\n",
        "        if i < window:\n",
        "            symmetry.append(0)\n",
        "            continue\n",
        "        \n",
        "        # Находим пики в окне\n",
        "        window_data = df['High'].iloc[i-window:i]\n",
        "        peaks_idx = []\n",
        "        for j in range(2, len(window_data)-2):\n",
        "            if (window_data.iloc[j] > window_data.iloc[j-1] and \n",
        "                window_data.iloc[j] > window_data.iloc[j+1]):\n",
        "                peaks_idx.append(j)\n",
        "        \n",
        "        # Если 3 пика, проверяем симметрию\n",
        "        if len(peaks_idx) >= 3:\n",
        "            peaks = [window_data.iloc[idx] for idx in peaks_idx[-3:]]\n",
        "            if peaks[1] > peaks[0] and peaks[1] > peaks[2]:  # средний выше\n",
        "                sym = 1 - abs(peaks[0] - peaks[2]) / (peaks[1] + 1e-10)\n",
        "                symmetry.append(sym)\n",
        "            else:\n",
        "                symmetry.append(0)\n",
        "        else:\n",
        "            symmetry.append(0)\n",
        "    \n",
        "    return symmetry\n",
        "\n",
        "print(\"Вычисление pattern-specific features...\")\n",
        "df_features['Peak_symmetry'] = calculate_peak_symmetry(df_features, window=30)\n",
        "\n",
        "# 2. DOUBLE TOP/BOTTOM features\n",
        "# Два пика на схожей цене\n",
        "def find_double_tops(df, window=20, tolerance=0.001):\n",
        "    \"\"\"Находит двойные вершины\"\"\"\n",
        "    double_top_signal = []\n",
        "    for i in range(len(df)):\n",
        "        if i < window:\n",
        "            double_top_signal.append(0)\n",
        "            continue\n",
        "        \n",
        "        window_highs = df['High'].iloc[i-window:i]\n",
        "        max_val = window_highs.max()\n",
        "        # Считаем сколько раз цена была близка к максимуму\n",
        "        near_max_count = ((window_highs > max_val * (1 - tolerance)) & \n",
        "                         (window_highs < max_val * (1 + tolerance))).sum()\n",
        "        \n",
        "        double_top_signal.append(1 if near_max_count >= 2 else 0)\n",
        "    \n",
        "    return double_top_signal\n",
        "\n",
        "df_features['Double_top_signal'] = find_double_tops(df_features, window=20)\n",
        "\n",
        "# 3. TRIANGLE/CHANNEL features\n",
        "# Slope of support and resistance\n",
        "def calculate_channel_slope(df, window=20):\n",
        "    \"\"\"Вычисляет наклон верхней и нижней границ канала\"\"\"\n",
        "    upper_slope = []\n",
        "    lower_slope = []\n",
        "    \n",
        "    for i in range(len(df)):\n",
        "        if i < window:\n",
        "            upper_slope.append(0)\n",
        "            lower_slope.append(0)\n",
        "            continue\n",
        "        \n",
        "        # Линейная регрессия для highs и lows\n",
        "        x = np.arange(window)\n",
        "        highs = df['High'].iloc[i-window:i].values\n",
        "        lows = df['Low'].iloc[i-window:i].values\n",
        "        \n",
        "        upper_coef = np.polyfit(x, highs, 1)[0]\n",
        "        lower_coef = np.polyfit(x, lows, 1)[0]\n",
        "        \n",
        "        upper_slope.append(upper_coef)\n",
        "        lower_slope.append(lower_coef)\n",
        "    \n",
        "    return upper_slope, lower_slope\n",
        "\n",
        "upper_slope, lower_slope = calculate_channel_slope(df_features, window=20)\n",
        "df_features['Channel_upper_slope'] = upper_slope\n",
        "df_features['Channel_lower_slope'] = lower_slope\n",
        "df_features['Channel_convergence'] = abs(np.array(upper_slope) - np.array(lower_slope))\n",
        "\n",
        "print(\"✅ Pattern-specific features: H&S symmetry, Double tops, Channel slopes\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ============================================================================\n",
        "# INDICATOR-BASED PATTERN FEATURES\n",
        "# ============================================================================\n",
        "\n",
        "# RSI Divergence (цена растет, RSI падает → медвежья дивергенция)\n",
        "def calculate_rsi_divergence(df, window=14):\n",
        "    \"\"\"Определяет RSI дивергенцию\"\"\"\n",
        "    bullish_div = []\n",
        "    bearish_div = []\n",
        "    \n",
        "    for i in range(len(df)):\n",
        "        if i < window:\n",
        "            bullish_div.append(0)\n",
        "            bearish_div.append(0)\n",
        "            continue\n",
        "        \n",
        "        # Тренд цены vs тренд RSI\n",
        "        price_slope = np.polyfit(\n",
        "            range(window), df['Close'].iloc[i-window:i].values, 1\n",
        "        )[0]\n",
        "        rsi_slope = np.polyfit(\n",
        "            range(window), df['RSI'].iloc[i-window:i].values, 1\n",
        "        )[0]\n",
        "        \n",
        "        # Бычья дивергенция: цена падает, RSI растет\n",
        "        if price_slope < 0 and rsi_slope > 0:\n",
        "            bullish_div.append(1)\n",
        "            bearish_div.append(0)\n",
        "        # Медвежья дивергенция: цена растет, RSI падает\n",
        "        elif price_slope > 0 and rsi_slope < 0:\n",
        "            bullish_div.append(0)\n",
        "            bearish_div.append(1)\n",
        "        else:\n",
        "            bullish_div.append(0)\n",
        "            bearish_div.append(0)\n",
        "    \n",
        "    return bullish_div, bearish_div\n",
        "\n",
        "bullish_div, bearish_div = calculate_rsi_divergence(df_features, window=14)\n",
        "df_features['RSI_bullish_divergence'] = bullish_div\n",
        "df_features['RSI_bearish_divergence'] = bearish_div\n",
        "\n",
        "# MACD Crossover\n",
        "df_features['MACD_crossover_bull'] = (\n",
        "    (df_features['MACD'] > df_features['MACD_signal']) & \n",
        "    (df_features['MACD'].shift(1) <= df_features['MACD_signal'].shift(1))\n",
        ").astype(int)\n",
        "\n",
        "df_features['MACD_crossover_bear'] = (\n",
        "    (df_features['MACD'] < df_features['MACD_signal']) & \n",
        "    (df_features['MACD'].shift(1) >= df_features['MACD_signal'].shift(1))\n",
        ").astype(int)\n",
        "\n",
        "# Bollinger Squeeze (низкая волатильность перед прорывом)\n",
        "df_features['BB_squeeze'] = (\n",
        "    df_features['BB_width'] < df_features['BB_width'].rolling(20).quantile(0.2)\n",
        ").astype(int)\n",
        "\n",
        "# RSI Overbought/Oversold zones\n",
        "df_features['RSI_overbought'] = (df_features['RSI'] > 70).astype(int)\n",
        "df_features['RSI_oversold'] = (df_features['RSI'] < 30).astype(int)\n",
        "\n",
        "print(\"✅ Indicator-based patterns: RSI divergence, MACD crossover, BB squeeze\")"
    ]
})

# ============================================================================
# FINAL CLEANUP
# ============================================================================

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Удаляем NaN (первые строки, где индикаторы не рассчитаны)\n",
        "print(f\"\\nПеред очисткой: {len(df_features)} строк\")\n",
        "df_features = df_features.dropna()\n",
        "print(f\"После удаления NaN: {len(df_features)} строк\")\n",
        "\n",
        "# Список всех фич\n",
        "feature_columns = [col for col in df_features.columns if col not in ['Open', 'High', 'Low', 'Close', 'Volume']]\n",
        "\n",
        "print(f\"\\n📊 FEATURE ENGINEERING COMPLETE!\")\n",
        "print(f\"\\nВсего создано фич: {len(feature_columns)}\")\n",
        "print(f\"\\nКатегории:\")\n",
        "trend_features = [c for c in feature_columns if any(x in c for x in ['SMA', 'EMA', 'MACD', 'ADX'])]\n",
        "momentum_features = [c for c in feature_columns if any(x in c for x in ['RSI', 'Stoch', 'ROC', 'Williams'])]\n",
        "volatility_features = [c for c in feature_columns if any(x in c for x in ['BB', 'ATR', 'Keltner'])]\n",
        "volume_features = [c for c in feature_columns if any(x in c for x in ['OBV', 'Volume'])]\n",
        "pattern_features = [c for c in feature_columns if any(x in c for x in \n",
        "                   ['Pivot', 'Candle', 'Price', 'Distance', 'Peak', 'Double', 'Channel', 'divergence', 'crossover', 'squeeze'])]\n",
        "\n",
        "print(f\"  Trend: {len(trend_features)}\")\n",
        "print(f\"  Momentum: {len(momentum_features)}\")\n",
        "print(f\"  Volatility: {len(volatility_features)}\")\n",
        "print(f\"  Volume: {len(volume_features)}\")\n",
        "print(f\"  Pattern-specific: {len(pattern_features)}\")\n",
        "\n",
        "print(f\"\\nРазмер финального датасета: {df_features.shape}\")"
    ]
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Визуализация некоторых индикаторов\n",
        "fig, axes = plt.subplots(4, 1, figsize=(16, 12))\n",
        "\n",
        "# Price with moving averages\n",
        "axes[0].plot(df_features.index, df_features['Close'], label='Close', linewidth=1.5)\n",
        "axes[0].plot(df_features.index, df_features['SMA_20'], label='SMA 20', alpha=0.7)\n",
        "axes[0].plot(df_features.index, df_features['SMA_50'], label='SMA 50', alpha=0.7)\n",
        "axes[0].set_title('Price with Moving Averages', fontsize=14, fontweight='bold')\n",
        "axes[0].legend()\n",
        "axes[0].grid(alpha=0.3)\n",
        "\n",
        "# RSI\n",
        "axes[1].plot(df_features.index, df_features['RSI'], label='RSI', color='purple', linewidth=1.5)\n",
        "axes[1].axhline(70, color='red', linestyle='--', alpha=0.5, label='Overbought')\n",
        "axes[1].axhline(30, color='green', linestyle='--', alpha=0.5, label='Oversold')\n",
        "axes[1].set_title('RSI (Relative Strength Index)', fontsize=14, fontweight='bold')\n",
        "axes[1].legend()\n",
        "axes[1].grid(alpha=0.3)\n",
        "\n",
        "# MACD\n",
        "axes[2].plot(df_features.index, df_features['MACD'], label='MACD', linewidth=1.5)\n",
        "axes[2].plot(df_features.index, df_features['MACD_signal'], label='Signal', linewidth=1.5)\n",
        "axes[2].bar(df_features.index, df_features['MACD_diff'], label='Histogram', alpha=0.3)\n",
        "axes[2].set_title('MACD', fontsize=14, fontweight='bold')\n",
        "axes[2].legend()\n",
        "axes[2].grid(alpha=0.3)\n",
        "\n",
        "# Bollinger Bands\n",
        "axes[3].plot(df_features.index, df_features['Close'], label='Close', linewidth=1.5)\n",
        "axes[3].plot(df_features.index, df_features['BB_upper'], label='BB Upper', alpha=0.5, linestyle='--')\n",
        "axes[3].plot(df_features.index, df_features['BB_middle'], label='BB Middle', alpha=0.5)\n",
        "axes[3].plot(df_features.index, df_features['BB_lower'], label='BB Lower', alpha=0.5, linestyle='--')\n",
        "axes[3].fill_between(df_features.index, df_features['BB_lower'], df_features['BB_upper'], alpha=0.1)\n",
        "axes[3].set_title('Bollinger Bands', fontsize=14, fontweight='bold')\n",
        "axes[3].legend()\n",
        "axes[3].grid(alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"✅ Технические индикаторы готовы!\")"
    ]
})

# Сохраняем обновленный ноутбук
notebook['cells'] = cells

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f'✅ Part 2 добавлена (Feature Engineering): {notebook_path}')
print(f'Всего ячеек: {len(cells)}')
print('Следующая часть: Task 1 - Price Forecasting...')
